* DONE flyspell 

[2015-10-12 Mon 11:35]


** installation

| steps |        |
|-------+--------|
|     1 | aspell |
|       |        |
|     2 | .emacs |
|       |        |
|       |        |


step 

1

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-text/aspell


2


(setq ispell-extra-args '("--sug-mode=fast"))
 (dolist (hook '(text-mode-hook))
      (add-hook hook (lambda () (flyspell-mode 1))))
    (dolist (hook '(change-log-mode-hook log-edit-mode-hook))
      (add-hook hook (lambda () (flyspell-mode -1))))




** Installing a spell checker

Emacs supports three spelling checkers by default: Hunspell, which is now widely used by popular free software such as LibreOffice, OpenOffice, Firefox and Thunderbird; GNU Aspell, which pays particular attention to quality of suggestions, and the original Ispell. If no spell checker is manually configured, Emacs will choose aspell over hunspell over ispell.

|   | Hunspell    | aspell        | ispell   |
|---+-------------+---------------+----------|
|   | popular     | quality       | original |
|   | libreoffice | emacs default |          |
|   | openoffice  |               |          |
|   | firefox     |               |          |

http://emacswiki.org/emacs/InteractiveSpell

GNU Aspell

Aspell was originally designed as a replacement for Ispell; its primary advantage today is the quality of its suggested replacements. This is particularly useful when used with flyspell-auto-correct-previous-word, where you can iterate through suggested spellings – it’s much more useful when the correct spelling is near the head of the list.

Aspell is a lot slower than Ispell; on modern machines, this probably doesn’t matter, but if you find editing is sluggish with flyspell-mode using Aspell, you can speed it up at the cost of reducing the quality of its suggestions with:

    (setq ispell-extra-args '("--sug-mode=fast"))


** .emacs


http://www.emacswiki.org/FlySpell


 (dolist (hook '(text-mode-hook))
      (add-hook hook (lambda () (flyspell-mode 1))))
    (dolist (hook '(change-log-mode-hook log-edit-mode-hook))
      (add-hook hook (lambda () (flyspell-mode -1))))




* emacs click url

| C-h v                       | default | change to          |
|-----------------------------+---------+--------------------|
| Browse Url Browser Function |         |                    |
|                             |         | browse-url-firefox |
|                             |         |                    |
|-----------------------------+---------+--------------------|
| Browse Url Firefox Program  |         |                    |
|                             |         | firefox-bin        |
|                             |         |                    |
|-----------------------------+---------+--------------------|
| Org File Apps               |         |                    |
|                             |         | firefox-bin %s     |
|                             |         |                    |
