


* gentoo 2 big files

|                  |                                        |
|                  | [2016-04-06 Wed 22:31]                 |
|------------------+----------------------------------------|
| stage3           | stage3-amd64-hardened-20160331.tar.bz2 |
|                  |                                        |
| portage snapshot |                                        |

http://ftp.jaist.ac.jp/pub/Linux/Gentoo/releases/amd64/autobuilds/current-stage3-amd64/hardened/

http://ftp.jaist.ac.jp/pub/Linux/Gentoo/snapshots/


** Verifying the downloaded files

https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Media

| file extension | contain               |
|----------------+-----------------------|
|                |                       |
| .CONTENTS      | files list            |
|                |                       |
| .DIGESTS       | checksums             |
|                |                       |
| .DIGEST.asc    | checksums + signature |
|                |                       |

| steps | validate  |                                 |
|-------+-----------+---------------------------------|
|    10 | signature |                                 |
|       |           | get public key                  |
|       |           |                                 |
|       |           | verify signature of .DIGEST.asc |
|       |           |                                 |
|-------+-----------+---------------------------------|
|    20 | checksum  |                                 |
|       |           | get HASH from .DIGEST.asc       |
|       |           |                                 |
|       |           | get HASH from the file          |
|       |           |                                 |
|       |           | compare the 2                   |

*** 10 validate signature

$

gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0xBB572E0E2D182910


gpg: requesting key 2D182910 from hkp server hkps.pool.sks-keyservers.net
gpg: /home/c5766/.gnupg/trustdb.gpg: trustdb created
gpg: key 2D182910: public key "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)


gpg --verify stage3-amd64-hardened-20160407.tar.bz2.DIGESTS.asc 


gpg: Signature made Fri 08 Apr 2016 04:41:03 PM CST using RSA key ID 2D182910
gpg: Good signature from "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 13EB BDBE DE7A 1277 5DFD  B1BA BB57 2E0E 2D18 2910

*** 20 validate checksum

grep -A 1 -i sha512 stage3-amd64-hardened-20160407.tar.bz2.DIGESTS.asc 

# SHA512 HASH
7a9d527f6de00153fe0d73458762f41dd34d369d53523ec03ad7602944b6ccaad325fb6374b1a8022b8c30554390672f1bfa06304e5198687a3cbd88ad8a3ddd  stage3-amd64-hardened-20160407.tar.bz2
--
# SHA512 HASH
bec5596a075b1e78e3d7779c425c49ecf84f2688ea054ebd0334d0e799db58f688ee14cbc62782cb3cc3ef5552da5d191cb661cae546ddee06b23f1b9f201a9a  stage3-amd64-hardened-20160407.tar.bz2.CONTENTS


sha512sum stage3-amd64-hardened-20160407.tar.bz2

7a9d527f6de00153fe0d73458762f41dd34d369d53523ec03ad7602944b6ccaad325fb6374b1a8022b8c30554390672f1bfa06304e5198687a3cbd88ad8a3ddd  stage3-amd64-hardened-20160407.tar.bz2

** stage4 cloud

https://mthode.org/posts/2016/Jan/stage4-tarballs-minimal-and-cloud/


https://gitweb.gentoo.org/proj/releng.git/tree/releases/weekly/specs/amd64/stage4-minimal.spec



* stage4

** steps

| generate excluding file |
|                         |
| generate tar            |
|                         |
| extract tar             |
|                         |
|                         |


|                  |   |
|------------------+---|
| stage3           |   |
|                  |   |
| portage snapshot |   |
|                  |   |
| kernel           |   |
|                  |   |
| tmpfs            |   |
|                  |   |
| zram             |   |
|                  |   |
| zswap            |   |
|                  |   |
| xorg             |   |
|                  |   |
| emacs            |   |
|                  |   |
| browser          |   |
|                  |   |
| wifi             |   |
|                  |   |
| hardened         |   |
|                  |   |
| docker           |   |
|                  |   |
| audio            |   |
|                  |   |
| livecd           |   |
|                  |   |
|                  |   |

** steps tmpfs h77md3h [2016-04-10 Sun 11:43]


| steps | aims                       |
|-------+----------------------------|
|    10 | generate working directory |
|       |                            |
|    20 | extract 2 big files        |
|       |                            |
|    30 | nano make.conf             |
|       |                            |
|    40 | chroot                     |
|       |                            |
|    50 | profile                    |
|       |                            |
|    60 | fstab                      |
|       |                            |
|    70 | kernel                     |
|       |                            |
|    80 | network                    |
|       |                            |
|    82 | basic packages             |
|       |                            |
|-------+----------------------------|
|       | stage4                     |
|       |                            |
|    90 | generate excluding file    |
|       |                            |
|    92 | generate tar               |
|       |                            |
|    93 | prepare the disk           |
|       |                            |
|    94 | extract tar                |
|       |                            |
|    96 | adjust grub                |


*** 10 generate working directory

#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp
#+BEGIN_SRC sh

mkdir gentoo

du -hd1 .  | grep gentoo

#+END_SRC

mkdir /tmp/gentoo

mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp/gentoo

mount | grep gentoo


#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp
#+BEGIN_SRC sh

mkdir gentoo

mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp/gentoo

du -hd1 .  | grep gentoo

mount | grep gentoo

#+END_SRC

#+RESULTS:
0	./gentoo
tmpfs on /tmp/gentoo type tmpfs (rw,noatime,nodiratime,size=5397036k,mode=777)


*** 20 extract 2 big files


#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp/gentoo
#+BEGIN_SRC sh

pwd

ls /mnt/fs1/stage3*

ls /mnt/fs1/portage*

#+END_SRC

#+RESULTS:
/tmp/gentoo
/mnt/fs1/stage3-amd64-hardened-20160331.tar.bz2
/mnt/fs1/stage3-amd64-hardened-20160407.tar.bz2
/mnt/fs1/portage-20160405.tar.xz




**** 14f [2016-04-10 Sun 11:49]

#

cd /tmp/gentoo

tar xvjpf /mnt/fs1/stage3-amd64-hardened-20160407.tar.bz2 --xattrs  





cd /tmp/gentoo/usr

tar xvpf /mnt/fs1/portage-20160405.tar.xz --xattrs


#+HEADERS: :results silent
#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp/gentoo
#+BEGIN_SRC sh

tar xvjpf /mnt/fs1/stage3-amd64-hardened-20160331.tar.bz2 --xattrs  

cd /tmp/gentoo/usr

tar xvpf /mnt/fs1/portage-20160405.tar.xz --xattrs

#+END_SRC




*** 30 nano make.conf

destdir=/tmp/gentoo

echo $destdir

nano $destdir/etc/portage/make.conf



MAKEOPTS="-j3"
PORTAGE_NICENESS=10

GENTOO_MIRRORS="http://ftp.twaren.net/Linux/Gentoo/ http://ftp.jaist.ac.jp/pub/Linux/Gentoo/ http://ftp.iij.ad.jp/pub/linux/gentoo/"



mkdir $destdir/etc/portage/repos.conf

cp $destdir/usr/share/portage/config/repos.conf $destdir/etc/portage/repos.conf/gentoo.conf

nano $destdir/etc/portage/repos.conf/gentoo.conf



[gentoo]
location = /usr/portage
sync-type = rsync
sync-uri = rsync://rsync.tw.gentoo.org/gentoo-portage
auto-sync = yes


*** 40 chroot

mount -o subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/fs3


mount -o subvol=fs2,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/fs2



destdir=/mnt/fs3

destdir=/tmp/gentoo

destdir=/mnt/sda/fs2

destdir=/mnt/fs2


cp -L /etc/resolv.conf $destdir/etc/

mount -t proc proc  $destdir/proc
mount --rbind /sys  $destdir/sys
mount --make-rslave $destdir/sys
mount --rbind /dev  $destdir/dev
mount --make-rslave $destdir/dev

mkdir $destdir/mnt/fs1

mount --bind /mnt/fs1 $destdir/mnt/fs1



chroot $destdir /bin/bash
source /etc/profile
export PS1="(chroot) $PS1"

emerge --sync


mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp

mkdir /var/tmp/portage 

mount -o size=90%,noatime,nodiratime,uid=portage,gid=portage,mode=775 -t tmpfs tmpfs /var/tmp/portage 




exit
cd

destdir=/tmp/gentoo


umount -l $destdir/dev{/shm,/pts,}
umount -l $destdir{/sys,/proc,}


*** 50 profile


eselect profile list

 [14]  hardened/linux/amd64 *

eselect profile set 14

eselect profile list



ls /usr/share/zoneinfo



echo "Asia/Taipei" > /etc/timezone

emerge --config sys-libs/timezone-data

nano -w /etc/locale.gen

locale-gen


eselect locale list

eselect locale set 2

eselect locale list

env-update && source /etc/profile


*** 60 fstab

blkid | grep sda

ls -l /dev/disk/by-uuid | grep sda


 UUID="8f88b023-a99c-4572-ae95-d762e8ec8a0a" UUID_SUB="930b9705-beaa-4306-b369-9ce3710d7c77" TYPE="btrfs"

lrwxrwxrwx 1 root root  9 Apr 10 17:12 8f88b023-a99c-4572-ae95-d762e8ec8a0a -> ../../sda



nano -w /etc/fstab

UUID=8f88b023-a99c-4572-ae95-d762e8ec8a0a    / btrfs subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

UUID=8f88b023-a99c-4572-ae95-d762e8ec8a0a    /mnt/fs1 btrfs subvol=fs1,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

tmpfs		/var/tmp/portage		tmpfs	size=6g,uid=portage,gid=portage,mode=775,noatime	0 0

tmpfs		/tmp		tmpfs	size=6g,defaults,noatime,nosuid,nodev,noexec,mode=1777	0 0



http://gaijin-nippon.blogspot.jp/2012/05/installing-archlinux-on-btrfs-with.html

# overlay /merged overlay noauto,x-systemd.automount,lowerdir=/lower,upperdir=/upper,workdir=/work 0 0
https://wiki.archlinux.org/index.php/Overlay_filesystem

mount -t overlayfs -o lowerdir=/filesystem.squashfs,upperdir=/overlay overlayfs /

http://askubuntu.com/questions/109413/how-do-i-use-overlayfs/109441#109441

overlay / overlay lowerdir=/mnt/rootfs1,upperdir=/mnt/rootfs2/upper,workdir=/mnt/rootfs2/work 0 0











*** 70 kernel

**** steps

| steps |                     |
|-------+---------------------|
|    20 | download            |
|       |                     |
|    30 | configure & compile |
|       |                     |
|    40 | deploy              |
|       |                     |
|    50 | grub                |


**** 20 download


emerge sys-kernel/hardened-sources -pv

 Install the kernel sources with the symlink USE flag active.  https://wiki.gentoo.org/wiki/Kernel/Configuration


echo "sys-kernel/hardened-sources symlink" >> /etc/portage/package.use/hardened-sources

emerge sys-kernel/hardened-sources -pv

emerge sys-kernel/hardened-sources


in host terminal:

tail -f /tmp/gentoo/var/log/emerge-fetch.log

tail -f /mnt/fs3/var/log/emerge-fetch.log


ls -l /usr/src/linux

ls -l /usr/src


lrwxrwxrwx 1 root root 20 Apr 10 16:14 /usr/src/linux -> linux-4.4.2-hardened

lrwxrwxrwx  1 root root  20 Apr 10 16:14 linux -> linux-4.4.2-hardened
drwxr-xr-x 25 root root 720 Apr 10 16:14 linux-4.4.2-hardened


**** 30 configure & compile

cd /usr/src/linux

make defconfig

make menuconfig

make && make modules_install


|       | 1 | 2 | 3 | 4 | 5 | 6 |                                       | defconfig |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| net   |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Network device suppor                 |           |   |           |
|       |   |   | v |   |   |   | Ethernet driver support               |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Atheros devices                       |           |   |           |
|       |   |   |   |   | v |   | Atheros L1C Gigabit Ethernet support  |           |   | h77md3h   |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Marvell devices                       |           |   |           |
|       |   |   |   |   | v |   | Marvell Yukon 2                       |           |   | b1 lenovo |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Realtek devices                       |           |   |           |
|       |   |   |   |   | v |   | Realtek 8169 gigabit                  |           |   | b1 asus   |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| btrfs |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | File systems                          |           |   |           |
|       |   | v |   |   |   |   | <*> Btrfs filesystem support          |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   | v |   |   |   |   | DOS/FAT/NT Filesystems  --->          |           |   |           |
|       |   |   | v |   |   |   | <M> NTFS file system support          |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| zram  |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Processor type and features           |           |   |           |
|       |   | v |   |   |   |   | Memory allocator for compressed pages | blank     | * |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Block devices                         |           |   |           |
|       |   |   | v |   |   |   | Compressed RAM block device support   | blank     | * |           |
|       |   |   |   | v |   |   | Enable LZ4 algorithm support          | blank     | * |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| temp  | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Hardware Monitoring support           |           |   |           |
|       |   |   | v |   |   |   | AMD Family 10h+ temperature sensor    | blank     | * | b1 asus   |
|       |   |   | v |   |   |   | ASUS ATK0110                          | blank     | * | b1 asus   |
|       |   |   |   |   |   |   |                                       |           |   |           |

btrfs


File systems  --->
    <*> Btrfs filesystem


proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge  sys-fs/btrfs-progs


zram

Processor type and features
 <*> Memory allocator for compressed pages 

Device Drivers > Block devices
<M>   Compressed RAM block device support  
 [*]     Enable LZ4 algorithm support 


What is the output of sensors-detect? Coretemp is only for Intel processors. You probably want k10temp.

https://bbs.archlinux.org/viewtopic.php?id=104723




**** 40 deploy

EXTENSION=20160410-hardened-net-zram

KERNELVER=4.4.2 

cp .config /boot/config-${KERNELVER}-${EXTENSION}
cp System.map /boot/System.map-${KERNELVER}-${EXTENSION}
cp arch/x86_64/boot/bzImage /boot/kernel-${KERNELVER}-${EXTENSION}
/usr/sbin/grub2-mkconfig -o /boot/grub/grub.cfg
cp -a .config ../${KERNELVER}-${EXTENSION}.config.bk



**** 50 grub

after deploy the stage4 in the final destination, configure grub




*** 80 Networking 

https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System


nano -w /etc/conf.d/hostname

hostname="14h77md3h"


nano -w /etc/conf.d/net


dns_domain_lo="14h77md3hnetwork"
config_enp3s0="dhcp"
config_enp2s0="dhcp"
config_enp1s0="dhcp"


emerge --noreplace net-misc/netifrc

cd /etc/init.d
ln -s net.lo net.enp3s0
rc-update add net.enp3s0 default

cd /etc/init.d
ln -s net.lo net.enp2s0
rc-update add net.enp2s0 default


cd /etc/init.d
ln -s net.lo net.enp1s0
rc-update add net.enp1s0 default

passwd

useradd -m -G users,wheel user1

passwd user1


nano -w /etc/conf.d/hwclock

clock="local"






*** 82 basic packages

emerge net-misc/dhcpcd

emerge sys-boot/grub

emerge proxychains


*** 90 generate excluding file 

nano /tmp/stage4.excl 


.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*



*** 92 generate tar 

cd /mnt/fs1

pwd

tar cvjf stage4_fs3_20160410.tar.bz2 / -X /tmp/stage4.excl  


*** 93 prepare the disk


#

mkfs.btrfs -f /dev/sda


mount -o defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/sda


cd /mnt/sda


btrfs subvolume create fs1

btrfs subvolume create fs2

btrfs subvolume create fs3

btrfs subvolume create fs4

btrfs subvolume create fs5



btrfs subvolume delete fs2


mount -o subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sdc /mnt/data


| rusb |                        |
|------+------------------------|
| fs1  |                        |
|      |                        |
| fs2  | [2016-04-10 Sun 16:32] |
|      | hardened               |
|      |                        |
| fs3  |                        |
|      |                        |
| fs4  |                        |
|      |                        |
| fs5  |                        |


**** prepare partitions btrfs and mount (old)


https://wiki.archlinux.org/index.php/Btrfs#Partitioning

# mkfs.btrfs /dev/sdX

mkfs.btrfs -f /dev/sdc

mount -o defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sdc /mnt/sdc

verify

mount | grep sdc

/dev/sdc on /mnt/sdc type btrfs (rw,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag)



http://gaijin-nippon.blogspot.jp/2012/05/installing-archlinux-on-btrfs-with.html

cd /mnt/sdd

btrfs subvolume create rootfs

mount -o subvol=rootfs,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sdd /mnt/gentoo

mount -o subvol=rootfs,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sdd /mnt/gentoo







*** 94 extract tar 

inside host

mount -o subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag \
/dev/sda /mnt/fs3

cd /mnt/fs3


**** h77md3h sda [2016-04-10 Sun 17:21]

ls /mnt/sda/fs1/sta* -l

cd /mnt/sda/fs2

pwd



tar -xvjpf /mnt/sda/fs1/stage4_fs3_20160410.tar.bz2







*** 96 adjust grub



grub2-install /dev/sda --recheck

grub2-mkconfig -o /boot/grub/grub.cfg


mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp

mount -o size=90%,noatime,nodiratime,uid=portage,gid=portage,mode=775 -t tmpfs tmpfs /var/tmp/portage 



exit
cd

destdir=/mnt/fs3

umount -l $destdir/dev{/shm,/pts,}
umount -l $destdir{/boot,/sys,/proc,}





** steps tmpfs M4A87TD/USB3 [2016-04-06 Wed 16:56]

| steps | aims                       |
|-------+----------------------------|
|    10 | generate working directory |
|       |                            |
|    20 | extract 2 big files        |
|       |                            |
|    30 | nano make.conf             |
|       |                            |
|    40 | chroot                     |
|       |                            |
|    50 | profile                    |
|       |                            |
|    60 | fstab                      |
|       |                            |
|    70 | kernel                     |
|       |                            |
|    80 | network                    |
|       |                            |
|    82 | basic packages             |
|       |                            |
|-------+----------------------------|
|       | stage4                     |
|       |                            |
|    90 | generate excluding file    |
|       |                            |
|    92 | generate tar               |
|       |                            |
|    94 | extract tar                |
|       |                            |
|    96 | adjust grub                |


*** 10 generate working directory

#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp
#+BEGIN_SRC sh

mkdir gentoo

du -hd1 .  | grep gentoo

#+END_SRC

#+RESULTS:
0	./gentoo
0	./gentoo



*** 20 extract 2 big files


#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp/gentoo
#+BEGIN_SRC sh

pwd

ls /mnt/fs1/stage3*

ls /mnt/fs1/portage*

#+END_SRC

#+RESULTS:
/tmp/gentoo
/mnt/fs1/stage3-amd64-hardened-20160331.tar.bz2
/mnt/fs1/portage-20160405.tar.xz


**** 14f

cd /tmp/gentoo

tar xvjpf /mnt/fs1/stage3-amd64-hardened-20160331.tar.bz2 --xattrs  

cd /tmp/gentoo/usr

tar xvpf /mnt/fs1/portage-20160405.tar.xz --xattrs


#+HEADERS: :results silent
#+HEADERS: :results raw
#+HEADERS: :dir /su::/tmp/gentoo
#+BEGIN_SRC sh

tar xvjpf /mnt/fs1/stage3-amd64-hardened-20160331.tar.bz2 --xattrs  

cd /tmp/gentoo/usr

tar xvpf /mnt/fs1/portage-20160405.tar.xz --xattrs

#+END_SRC




*** 30 nano make.conf

destdir=/tmp/gentoo

echo $destdir


nano $destdir/etc/portage/make.conf

MAKEOPTS="-j3"
PORTAGE_NICENESS=10

GENTOO_MIRRORS="http://ftp.twaren.net/Linux/Gentoo/ http://ftp.jaist.ac.jp/pub/Linux/Gentoo/ http://ftp.iij.ad.jp/pub/linux/gentoo/"



mkdir $destdir/etc/portage/repos.conf

cp $destdir/usr/share/portage/config/repos.conf $destdir/etc/portage/repos.conf/gentoo.conf

nano $destdir/etc/portage/repos.conf/gentoo.conf

[gentoo]
location = /usr/portage
sync-type = rsync
sync-uri = rsync://rsync.tw.gentoo.org/gentoo-portage
auto-sync = yes


*** 40 chroot

mount -o subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/fs3

destdir=/mnt/fs3

destdir=/tmp/gentoo



cp -L /etc/resolv.conf $destdir/etc/

mount -t proc proc  $destdir/proc
mount --rbind /sys  $destdir/sys
mount --make-rslave $destdir/sys
mount --rbind /dev  $destdir/dev
mount --make-rslave $destdir/dev

mkdir $destdir/mnt/fs1

mount --bind /mnt/fs1 $destdir/mnt/fs1



chroot $destdir /bin/bash
source /etc/profile
export PS1="(chroot) $PS1"

emerge --sync


mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp

mount -o size=90%,noatime,nodiratime,uid=portage,gid=portage,mode=775 -t tmpfs tmpfs /var/tmp/portage 




exit
cd

destdir=/tmp/gentoo


umount -l $destdir/dev{/shm,/pts,}
umount -l $destdir{/sys,/proc,}


*** 50 profile


eselect profile list

 [14]  hardened/linux/amd64 *

eselect profile set 14

eselect profile list



ls /usr/share/zoneinfo



echo "Asia/Taipei" > /etc/timezone

emerge --config sys-libs/timezone-data

nano -w /etc/locale.gen

locale-gen


eselect locale list

eselect locale set 2

eselect locale list

env-update && source /etc/profile


*** 60 fstab

blkid | grep sda

ls -l /dev/disk/by-uuid | grep sda


/dev/sda: UUID="cdc17294-c2aa-414f-bf3c-83f36a3e503a" UUID_SUB="114232ef-f0d2-48b2-936a-ccfc531e36d3" TYPE="btrfs" PTTYPE="dos"

lrwxrwxrwx 1 root root  9 Apr  7  2016 cdc17294-c2aa-414f-bf3c-83f36a3e503a -> ../../sda



nano -w /etc/fstab

UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a   / btrfs subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a   /mnt/fs1 btrfs subvol=fs1,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

tmpfs   /var/tmp/portage        tmpfs   uid=portage,gid=portage,mode=0775,size=5g,noatime    0 0

tmpfs   /tmp         tmpfs   size=5g,mode=777          0  0




http://gaijin-nippon.blogspot.jp/2012/05/installing-archlinux-on-btrfs-with.html

# overlay /merged overlay noauto,x-systemd.automount,lowerdir=/lower,upperdir=/upper,workdir=/work 0 0
https://wiki.archlinux.org/index.php/Overlay_filesystem

mount -t overlayfs -o lowerdir=/filesystem.squashfs,upperdir=/overlay overlayfs /

http://askubuntu.com/questions/109413/how-do-i-use-overlayfs/109441#109441

overlay / overlay lowerdir=/mnt/rootfs1,upperdir=/mnt/rootfs2/upper,workdir=/mnt/rootfs2/work 0 0











*** 70 kernel

**** steps

| steps |                     |
|-------+---------------------|
|    20 | download            |
|       |                     |
|    30 | configure & compile |
|       |                     |
|    40 | deploy              |
|       |                     |
|    50 | grub                |


**** 20 download


emerge sys-kernel/hardened-sources -pv

 Install the kernel sources with the symlink USE flag active.  https://wiki.gentoo.org/wiki/Kernel/Configuration


echo "sys-kernel/hardened-sources symlink" >> /etc/portage/package.use/hardened-sources

emerge sys-kernel/hardened-sources -pv

emerge sys-kernel/hardened-sources


in host terminal:

tail -f /tmp/gentoo/var/log/emerge-fetch.log

tail -f /mnt/fs3/var/log/emerge-fetch.log


ls -l /usr/src/linux

ls -l /usr/src


lrwxrwxrwx  1 root root  20 Apr  7 11:47 linux -> linux-4.4.2-hardened
drwxr-xr-x 25 root root 720 Apr  7 11:47 linux-4.4.2-hardened


**** 30 configure & compile

cd /usr/src/linux

make defconfig

make menuconfig

make && make modules_install


|       | 1 | 2 | 3 | 4 | 5 | 6 |                                       | defconfig |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| net   |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Network device suppor                 |           |   |           |
|       |   |   | v |   |   |   | Ethernet driver support               |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Atheros devices                       |           |   |           |
|       |   |   |   |   | v |   | Atheros L1C Gigabit Ethernet support  |           |   | h77md3h   |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Marvell devices                       |           |   |           |
|       |   |   |   |   | v |   | Marvell Yukon 2                       |           |   | b1 lenovo |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   |   |   | v |   |   | Realtek devices                       |           |   |           |
|       |   |   |   |   | v |   | Realtek 8169 gigabit                  |           |   | b1 asus   |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| btrfs |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | File systems                          |           |   |           |
|       |   | v |   |   |   |   | <*> Btrfs filesystem support          |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       |   | v |   |   |   |   | DOS/FAT/NT Filesystems  --->          |           |   |           |
|       |   |   | v |   |   |   | <M> NTFS file system support          |           |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| zram  |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Processor type and features           |           |   |           |
|       |   | v |   |   |   |   | Memory allocator for compressed pages | blank     |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|       | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Block devices                         |           |   |           |
|       |   |   | v |   |   |   | Compressed RAM block device support   | blank     |   |           |
|       |   |   |   | v |   |   | Enable LZ4 algorithm support          | blank     |   |           |
|       |   |   |   |   |   |   |                                       |           |   |           |
|-------+---+---+---+---+---+---+---------------------------------------+-----------+---+-----------|
| temp  | v |   |   |   |   |   | Device Drivers                        |           |   |           |
|       |   | v |   |   |   |   | Hardware Monitoring support           |           |   |           |
|       |   |   | v |   |   |   | AMD Family 10h+ temperature sensor    | blank     | * | b1 asus   |
|       |   |   | v |   |   |   | ASUS ATK0110                          | blank     | * | b1 asus   |
|       |   |   |   |   |   |   |                                       |           |   |           |

btrfs


File systems  --->
    <*> Btrfs filesystem


proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge  sys-fs/btrfs-progs


zram

Processor type and features
 <*> Memory allocator for compressed pages 

Device Drivers > Block devices
<M>   Compressed RAM block device support  
 [*]     Enable LZ4 algorithm support 


What is the output of sensors-detect? Coretemp is only for Intel processors. You probably want k10temp.

https://bbs.archlinux.org/viewtopic.php?id=104723




**** 40 deploy

EXTENSION=20160407-hardened-net-zram

EXTENSION=20160408-hardened-net-zram-disable_legacy_fbdev 

EXTENSION=20160408-hardened-net-zram-nouveau_buildin

EXTENSION=20160411-hardened-net-zram-nouveau_buildin-amdtemp-hda-zswap

KERNELVER=4.4.2 

cp .config /boot/config-${KERNELVER}-${EXTENSION}
cp System.map /boot/System.map-${KERNELVER}-${EXTENSION}
cp arch/x86_64/boot/bzImage /boot/kernel-${KERNELVER}-${EXTENSION}
/usr/sbin/grub2-mkconfig -o /boot/grub/grub.cfg
cp -a .config ../${KERNELVER}-${EXTENSION}.config.bk



**** 50 grub

after deploy the stage4 in the final destination, configure grub




*** 80 Networking 

https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/System


nano -w /etc/conf.d/hostname

hostname="b1asus"


nano -w /etc/conf.d/net


dns_domain_lo="b1network"
config_enp3s0="dhcp"
config_enp2s0="dhcp"
config_enp1s0="dhcp"


emerge --noreplace net-misc/netifrc

cd /etc/init.d
ln -s net.lo net.enp3s0
rc-update add net.enp3s0 default

cd /etc/init.d
ln -s net.lo net.enp2s0
rc-update add net.enp2s0 default


cd /etc/init.d
ln -s net.lo net.enp1s0
rc-update add net.enp1s0 default

passwd

useradd -m -G users,wheel c5766 

passwd c5766


nano -w /etc/conf.d/hwclock

clock="local"






*** 82 basic packages

emerge net-misc/dhcpcd

emerge sys-boot/grub

emerge proxychains


*** 90 generate excluding file 

nano /tmp/stage4.excl 


.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*



*** 92 generate tar 

cd /mnt/fs1

pwd

tar cvjf stage4_fs3_20160407.tar.bz2 / -X /tmp/stage4.excl  


*** 94 extract tar 

inside host

mount -o subvol=fs3,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag \
/dev/sda /mnt/fs3

cd /mnt/fs3

tar -xvjpf /mnt/fs1/stage4_fs3_20160407.tar.bz2




*** 96 adjust grub



grub2-install /dev/sda --recheck

grub2-mkconfig -o /boot/grub/grub.cfg


mount -o size=90%,noatime,nodiratime,mode=777 -t tmpfs tmpfs /tmp

mount -o size=90%,noatime,nodiratime,uid=portage,gid=portage,mode=775 -t tmpfs tmpfs /var/tmp/portage 



exit
cd

destdir=/mnt/fs3

umount -l $destdir/dev{/shm,/pts,}
umount -l $destdir{/boot,/sys,/proc,}




** steps fs3 M4A87TD/USB3 [2016-03-31 Thu 17:57]




| steps |                         |
|-------+-------------------------|
|    10 | btrfs                   |
|       |                         |
|    20 | generate excluding file |
|       |                         |
|    30 | generate tar            |
|       |                         |
|    40 | extract tar             |
|       |                         |
|    50 | adjust grub             |
|       |                         |
|    60 | adjust fstab            |
|       |                         |


*** 10 btrfs

[2016-03-29 Tue 16:38]


sda                         8:0    0 279.5G  0 disk 
├─sda1                      8:1    0     2M  0 part 
├─sda2                      8:2    0   122M  0 part 
├─sda3                      8:3    0   488M  0 part 
├─sda4                      8:4    0   8.7G  0 part 
├─sda5                      8:5    0   9.3G  0 part 
└─sda6                      8:6    0 260.9G  0 part 
sdb                         8:16   0 465.8G  0 disk 
└─sdb1                      8:17   0 445.3G  0 part 

mkfs.btrfs -f /dev/sda

mount -o defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/sda

cd /mnt/sda

btrfs subvolume create fs1

btrfs subvolume create fs2

btrfs subvolume create fs3

btrfs subvolume create fs4

btrfs subvolume create fs5


*** 20 generate excluding file 


/tmp/stage4.excl 


.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*



*** 30 generate tar 


tar cvjf stage4_fs3b_20160329.tar.bz2 / -X /tmp/stage4.excl  


*** 40 extract tar 

cd /tmp/gentoo

tar -xvjpf /mnt/fs1/stage4_fs3b_20160329.tar.bz2 

*** 50 adjust grub


mount -t proc proc  /mnt/sda/fs2/proc
mount --rbind /sys  /mnt/sda/fs2/sys
mount --make-rslave /mnt/sda/fs2/sys
mount --rbind /dev  /mnt/sda/fs2/dev
mount --make-rslave /mnt/sda/fs2/dev


chroot /mnt/sda/fs2/ /bin/bash
source /etc/profile
export PS1="(chroot) $PS1"


grub2-install /dev/sda --recheck


grub2-mkconfig -o /boot/grub/grub.cfg

grub2-mkconfig -o /mnt/sda/fs2/boot/grub/grub.cfg


exit
cd

umount -l /mnt/sda/fs2/dev{/shm,/pts,}
umount -l /mnt/sda/fs2{/boot,/sys,/proc,}


*** 60 adjust fstab

blkid


UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a/ btrfs subvol=fs2,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a/mnt/fs1 btrfs subvol=fs1,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

tmpfs           /var/tmp/portage        tmpfs   uid=portage,gid=portage,mode=0775,size=90%,noatime    0 0
tmpfs   /tmp         tmpfs   nodev,nosuid,size=90%          0  0




** steps wusb to M4A87TD/USB3 [2016-03-29 Tue 16:33]



| steps |                         |
|-------+-------------------------|
|    10 | btrfs                   |
|       |                         |
|    20 | generate excluding file |
|       |                         |
|    30 | generate tar            |
|       |                         |
|    40 | extract tar             |
|       |                         |
|    50 | adjust grub             |
|       |                         |
|    60 | adjust fstab            |
|       |                         |


*** 10 btrfs

[2016-03-29 Tue 16:38]


sda                         8:0    0 279.5G  0 disk 
├─sda1                      8:1    0     2M  0 part 
├─sda2                      8:2    0   122M  0 part 
├─sda3                      8:3    0   488M  0 part 
├─sda4                      8:4    0   8.7G  0 part 
├─sda5                      8:5    0   9.3G  0 part 
└─sda6                      8:6    0 260.9G  0 part 
sdb                         8:16   0 465.8G  0 disk 
└─sdb1                      8:17   0 445.3G  0 part 

mkfs.btrfs -f /dev/sda

mount -o defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/sda

cd /mnt/sda

btrfs subvolume create fs1

btrfs subvolume create fs2

btrfs subvolume create fs3

btrfs subvolume create fs4

btrfs subvolume create fs5


*** 20 generate excluding file 


/tmp/stage4.excl 


.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*
/etc/ssh/ssh_host_*
/usr/src/*
/usr/portage/*
/home/c5766/Mail/*
/home/c5766/downloads/*
/home/c5766/Downloads/*
/home/c5766/News/*


*** 30 generate tar 


tar cvjf /mnt/sda/fs1/stage4_wusb_20160329.tar.bz2 / -X /tmp/stage4.excl  


*** 40 extract tar 

cd /mnt/sda/fs2/

tar -xvjpf /mnt/sda/fs1/stage4_wusb_20160329.tar.bz2


*** 50 adjust grub


mount -t proc proc  /mnt/sda/fs2/proc
mount --rbind /sys  /mnt/sda/fs2/sys
mount --make-rslave /mnt/sda/fs2/sys
mount --rbind /dev  /mnt/sda/fs2/dev
mount --make-rslave /mnt/sda/fs2/dev


chroot /mnt/sda/fs2/ /bin/bash
source /etc/profile
export PS1="(chroot) $PS1"


grub2-install /dev/sda --recheck


grub2-mkconfig -o /boot/grub/grub.cfg

grub2-mkconfig -o /mnt/sda/fs2/boot/grub/grub.cfg


exit
cd

umount -l /mnt/sda/fs2/dev{/shm,/pts,}
umount -l /mnt/sda/fs2{/boot,/sys,/proc,}


*** 60 adjust fstab

blkid


UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a/ btrfs subvol=fs2,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

UUID=cdc17294-c2aa-414f-bf3c-83f36a3e503a/mnt/fs1 btrfs subvol=fs1,defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag 0 0

tmpfs           /var/tmp/portage        tmpfs   uid=portage,gid=portage,mode=0775,size=90%,noatime    0 0
tmpfs   /tmp         tmpfs   nodev,nosuid,size=90%          0  0



** original

http://www.gentoo-wiki.info/HOWTO_Custom_Stage4

stage4.excl contents:

.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*
/etc/ssh/ssh_host_*
/usr/src/*
/usr/portage/*
/path/to/save/at/stage4.tar.bz2




# tar cvjf /path/to/save/at/stage4.tar.bz2 / -X stage4.excl

tar cvjf /mnt/sdb6/gentoo/stage4.tar.bz2 / -X stage4.excl

  
** my modification 1

nano stage4.excl

.bash_history
/mnt/*
/tmp/*
/proc/*
/sys/*
/dev/*
/etc/ssh/ssh_host_*

tar cvjf stage4_20160121.tar.bz2 / -X stage4.excl  

mount the target fs and cd inside.

tar -xvjpf /mnt/sdb/fs1/stage4_20160121.tar.bz2




* packages

** inventory

|               | h77md3h fs2             | M4A87TD/USB3 280g/fs3  |
|---------------+-------------------------+------------------------|
| shell group   |                         |                        |
|               |                         |                        |
| proxychains   |                         | [2016-04-07 Thu 15:13] |
|               |                         |                        |
| grub          |                         | [2016-04-07 Thu 15:13] |
|               |                         |                        |
| dhcpcd        |                         | [2016-04-07 Thu 15:13] |
|               |                         |                        |
| keychain      |                         |                        |
|               |                         |                        |
| parallel      |                         |                        |
|               |                         |                        |
| git           | [2016-04-10 Sun 20:54]  |                        |
|               |                         |                        |
| mc            |                         |                        |
|               |                         |                        |
| tree          |                         |                        |
|               |                         |                        |
| megatools     |                         |                        |
|               |                         |                        |
|---------------+-------------------------+------------------------|
| xorg group    |                         |                        |
|               |                         |                        |
| xorg-server   | [2016-04-10 Sun 21:22]  | [2016-04-07 Thu 15:13] |
|               |                         |                        |
| xorg-drivers  | automatically installed |                        |
| intel         |                         |                        |
|               |                         |                        |
| mesa          | automatically installed |                        |
| i915          |                         |                        |
|               |                         |                        |
| xrandr        | [2016-04-10 Sun 22:22]  | [2016-04-07 Thu 16:12] |
|               |                         |                        |
| xterm         |                         | [2016-04-07 Thu 16:12] |
|               |                         |                        |
| spectrwm      |                         | [2016-04-07 Thu 16:12] |
|               |                         |                        |
| vnc           |                         |                        |
|               |                         |                        |
|---------------+-------------------------+------------------------|
| editors       |                         |                        |
|               |                         |                        |
| emacs         |                         | [2016-04-07 Thu 17:06] |
|               |                         |                        |
| google-chrome |                         | [2016-04-07 Thu 17:11] |
|               |                         |                        |
| firefox       |                         |                        |
|               |                         |                        |
| pdfshuffler   |                         |                        |
|               |                         |                        |
| libreoffice   |                         |                        |
|               |                         |                        |
| gimp          |                         |                        |
|               |                         |                        |
| imagemagick   |                         |                        |
|               |                         |                        |
|---------------+-------------------------+------------------------|
| audio         |                         |                        |
|               |                         |                        |
|               |                         |                        |

** audio

*** alsa-lib

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge media-libs/alsa-lib

** shell group


*** proxychains


emerge proxychains


*** dhcpcd

emerge net-misc/dhcpcd







*** grub

emerge grub

do the installation and generation of grub menu after all the files in the final /dev/sdx place.
otherwise, it will failed during preparation (tar).

grub2-install /dev/sda

grub2-mkconfig -o /boot/grub/grub.cfg


**** resolution

***** steps

| steps |                                       |
|-------+---------------------------------------|
|       | modify /etc/default/grub              |
|       | GRUB_GFXMODE=1024x768                 |
|       |                                       |
|       | grub2-mkconfig -o /boot/grub/grub.cfg |

***** reference


http://askubuntu.com/questions/54067/how-do-i-safely-change-grub2-screen-resolution

To do this safely requires two steps.

Step 1: find the preferred mode
Reboot and press and hold Shift to display your grub. Press C to enter console mode. Then type:

$ vbeinfo
This will display various stuff how grub recognizes your display. At the bottom is "preferred mode" - in your case it should say 1280x800. Note down the value.

Note: sometimes, some buggy video cards incorrectly give Grub the wrong preferred resolution - if the preferred mode is much higher than you were expecting, then select the nearest mode in the list displayed that you were expecting.

Press Esc to return to grub and press Enter to boot.

Step 2: Setting the resolution in grub
Reach for your terminal and type

$ sudo nano /etc/default/grub
find the line

#GRUB_GFXMODE=640x480
remove the # and change 640x480 with the preferred mode you wrote down. E.g.:

GRUB_GFXMODE=1280x800
save, then type

$ sudo update-grub





**** zram


http://askubuntu.com/questions/361320/how-can-i-enable-zswap

https://help.ubuntu.com/community/Grub2/Setup#A.2BAC8-etc.2BAC8-default.2BAC8-grub

nano /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="rootwait"

GRUB_CMDLINE_LINUX_DEFAULT="rootwait zswap.enabled=1 zswap.compressor=lz4"

GRUB_CMDLINE_LINUX_DEFAULT="zswap.enabled=1 zswap.compressor=lz4"



*** tlsdate

https://github.com/ioerror/tlsdate/


emerge --ask net-misc/tlsdate


/etc/init.d/tlsdate start

rc-update add tlsdate default

tlsdate -V -n -H www.google.com.tw socks5://127.0.0.1:1080


**** openntpd gentoo

https://wiki.gentoo.org/wiki/OpenNTPD


proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge --ask net-misc/openntpd

/etc/ntpd.conf

/etc/init.d/ntpd start

/etc/init.d/ntpd stop

/etc/init.d/ntpd restart

rc-update add ntpd default

rc-update delete ntpd default




proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge --ask net-misc/openntpd

4.0_pre20080406 missing ntpctl



equery y openntpd
Keywords for net-misc/openntpd:
                      |                               | u   |  
                      | a a   a         n   p     s   | n   |  
                      | l m   r h i m m i   p s   p   | u s | r
                      | p d a m p a 6 i o p c 3   a x | s l | e
                      | h 6 r 6 p 6 8 p s p 6 9 s r 8 | e o | p
                      | a 4 m 4 a 4 k s 2 c 4 0 h c 6 | d t | o
----------------------+-------------------------------+-----+-------
[I]4.0_pre20080406    | + + + + + + o ~ o + + + + + + | o 0 | gentoo
            5.7_p4-r1 | ~ ~ ~ ~ ~ ~ o ~ o ~ ~ ~ ~ ~ ~ | o   | gentoo


emerge --ask --autounmask-write =net-misc/openntpd-5.7_p4-r1

dispatch-conf


emerge --ask  =net-misc/openntpd-5.7_p4-r1


ntpd -s


ntpctl -sa

**** software hardware clock

https://wiki.gentoo.org/wiki/System_time

| clock | software  | hardware            |                 |
|-------+-----------+---------------------+-----------------|
|       | unix time |                     |                 |
|       |           | real-time clock RTC |                 |
|       |           | mainboard           |                 |
|       |           |                     |                 |
|-------+-----------+---------------------+-----------------|
|       |           | 2 standards         |                 |
|-------+-----------+---------------------+-----------------|
|       |           | localtime           |                 |
|       |           |                     | time zone + DST |
|       |           |                     | Windows         |
|       |           |                     |                 |
|-------+-----------+---------------------+-----------------|
|       |           | UTC time            |                 |
|       |           |                     |                 |


cat /etc/timezone
Asia/Taipei

emerge --config timezone-data



https://wiki.gentoo.org/wiki/System_time

|       | software clock    | hardware clock                   |   |
|-------+-------------------+----------------------------------+---|
|       |                   | real-time clock, RTC, CMOS clock |   |
|       |                   |                                  |   |
|       | kernel clock      |                                  |   |
|       | system clock      |                                  |   |
|       | since 1 1 1970    |                                  |   |
|       | unix time         |                                  |   |
|       |                   |                                  |   |
|-------+-------------------+----------------------------------+---|
|       | date              | hwclock -r                       |   |
|       | date -R           |                                  |   |
|       | date -u           |                                  |   |
|       |                   |                                  |   |
|-------+-------------------+----------------------------------+---|
| store | yyyymmddhhmmss    | yyyymmddhhmmss                   |   |
|       | DST localtime UTC |                                  |   |
|       |                   |                                  |   |



| hardware clock | localtime      | UTC time  |
|----------------+----------------+-----------|
|                | timezone + DST |           |
|                |                | preferred |
|                | ms Windows     |           |
| #              |                |           |
| hwclock -r     |                |           |
|                |                |           |

|        |                            |   |   |   |
|        | UTC                        |   |   |   |
|--------+----------------------------+---+---+---|
|        | Coordinated Universal Time |   |   |   |
|        | 世界標準時間               |   |   |   |
|        | 世界協調時間               |   |   |   |
|        | internet                   |   |   |   |
| taipei | UTC+8                      |   |   |   |
|        |                            |   |   |   |
|        | date -u                    |   |   |   |
|        |                            |   |   |   |

**** CST

| CST       | Central Standard Time | China Standard Time |
|           |                       |                     |
|-----------+-----------------------+---------------------|
|           | UTC-6                 | UTC+8               |
| reference | 1                     | 2                   |
|           |                       |                     |


date; date -u


reference

1

https://en.wikipedia.org/wiki/Central_Time_Zone


2

https://en.wikipedia.org/wiki/Time_in_China





****  set the hardware clock to the current system clock: 

https://wiki.gentoo.org/wiki/System_time#systemd

hwclock --systohc

hwclock --show


hwclock --show; date; tlsdate -V -n -H encrypted.google.com


tlsdate -V -n -H encrypted.google.com

tlsdate -V -n 

tlsdate -V -n -H www.google.com
tlsdate -V -n -H www.google.com socks5://127.0.0.1:1080

tlsdate -V -n -H www.google.com.tw
tlsdate -V -n -H www.google.com.tw socks5://127.0.0.1:1080


tlsdate -V -n -H www.google.com

tlsdate -V -n -H www.google.de 
tlsdate -V -n -H www.google.de socks5://127.0.0.1:1080

tlsdate -V -n -H www.google.de socks5://127.0.0.1:1080

tlsdate -V -n -H www.google.de socks5://127.0.0.1:1080

tlsdate -V -n -H www.google.com.tw



*** sys-boot/mbr

emerge sys-boot/mbr


*** parallel

emerge  sys-process/parallel

**** my modification

ls -1 *.tif | parallel convert '{}' '{.}.jpg'

ls -1 *.tif | parallel convert '{}' '{.}.jpg'

ls -1 *.tif | parallel convert '{}' -rotate -90 '{.}-90.jpg'

**** examples

http://superuser.com/questions/71028/batch-converting-png-to-jpg-in-linux

The simplest solution is like most already posted. A simple bash for loop.

for i in *.png ; do convert "$i" "${i%.*}.jpg" ; done
For some reason I tend to avoid loops in bash so here is a more unixy xargs approach, using bash for the name-mangling.

ls -1 *.png | xargs -n 1 bash -c 'convert "$0" "${0%.*}.jpg"'
The one I use. It uses GNU Parallel to run multiple jobs at once, giving you a performance boost. It is installed by default on many systems and is almost definitely in your repo (it is a good program to have around).

ls -1 *.png | parallel convert '{}' '{.}.jpg'
The number of jobs defaults to the number of processes you have. I found better CPU usage using 3 jobs on my dual-core system.

ls -1 *.png | parallel -j 3 convert '{}' '{.}.jpg'
And if you want some stats (an ETA, jobs completed, average time per job...)

ls -1 *.png | parallel --eta convert '{}' '{.}.jpg'
There is also an alternative syntax if you are using GNU Parallel.

parallel convert '{}' '{.}.jpg' ::: *.png
And a similar syntax for some other versions (including debian).

parallel convert '{}' '{.}.jpg' -- *.png




*** git


emerge dev-vcs/git

*** mc

emerge app-misc/mc





*** tree


emerge app-text/tree



*** megatools

echo "net-misc/megatools fuse" >> /etc/portage/package.use/fuse

emerge -pv megatools

emerge net-misc/megatools --autounmask-write 

dispatch-conf


**** megarc

http://albertolarripa.com/2013/07/10/megatools-synchronizing-your-backups-to-mega/

cat /root/.megarc 
[Login]
Username = email@albertolarripa.com
Password = yourpassword




** xorg group
   
*** x11-base/xorg-server

| kernel               |
|                      |
| make.conf            |
|                      |
| download and compile |

**** kernel

| 1 | 2 | 3 | 4 | 5 | kernel option                     | defconfig | change to | reference |
|   |   |   |   |   |                                   |           |           |           |
|---+---+---+---+---+-----------------------------------+-----------+-----------+-----------|
| v |   |   |   |   | Device Drivers                    |           |           |           |
|   | v |   |   |   | Input device support              |           |           |           |
|   |   | v |   |   | Event interface                   | *         |           |           |
|---+---+---+---+---+-----------------------------------+-----------+-----------+-----------|
|   |   |   |   |   |                                   |           |           |           |
|   | v |   |   |   | Graphics support                  |           |           |           |
|   |   | v |   |   | Frame buffer Devices              |           |           |           |
|   |   |   | v |   | Support for frame buffer devices  |           |           |           |
|   |   |   |   | v | Enable firmware EDID              | none      |           |           |
|---+---+---+---+---+-----------------------------------+-----------+-----------+-----------|
|   |   |   |   |   |                                   |           |           |           |
|   |   | v |   |   | Console display driver support    |           |           |           |
|   |   |   | v |   | Framebuffer Console support       | *         |           |           |
|---+---+---+---+---+-----------------------------------+-----------+-----------+-----------|
|   |   |   |   |   |                                   |           |           |           |
|   |   | v |   |   | Direct Rendering Manager (XFree86 |           |           |           |
|   |   |   | v |   | Enable legacy fbdev support for   | *         |           |         2 |
|---+---+---+---+---+-----------------------------------+-----------+-----------+-----------|
|   |   |   |   |   |                                   |           |           |           |
|   |   | v |   |   | Nouveau (NVIDIA) cards            | none      | M         |           |
|   |   |   |   |   |                                   |           | *         |           |
|   |   | v |   |   | Intel 8xx/9xx/G3x/G4x/HD Graphics |           | M         |   h77md3h |
|   |   |   |   |   |                                   |           |           |           |

reference


1

https://wiki.gentoo.org/wiki/Xorg/Guide


2

https://wiki.gentoo.org/wiki/Nouveau


3

https://forums.gentoo.org/viewtopic-p-6655021.html



**** make.conf

nano /etc/portage/make.conf


Sample make.conf entries
## (For mouse, keyboard, and Synaptics touchpad support)
INPUT_DEVICES="evdev synaptics"
## (For nVidia cards)
VIDEO_CARDS="nouveau"
## (For AMD/ATI cards)
VIDEO_CARDS="radeon"

INPUT_DEVICES="evdev"

VIDEO_CARDS="nouveau"

VIDEO_CARDS="intel i915"



**** download and compile

emerge --ask x11-base/xorg-server

gpasswd -a user1 video  # for 


**** errors

[  1072.674] (EE) Failed to load module "nv" (module does not exist, 0)

[  1072.685] (EE) open /dev/dri/card0: No such file or directory



*** xorg-drivers

emerge xorg-drivers  # for intel

*** mesa

emerge media-libs/mesa # for i915




*** xrandr

emerge  x11-apps/xrandr



*** xterm

emerge x11-terms/xterm

 * Messages for package media-fonts/liberation-fonts-2.00.1-r1:

 * The following fontconfig configuration files have been installed:
 * 
 *   60-liberation.conf
 * 
 * Use `eselect fontconfig` to enable/disable them.

 * Messages for package media-libs/fontconfig-2.11.1-r2:

eselect fontconfig enable 60-liberation.conf

eselect fontconfig list





*** spectrwm

emerge spectrwm

https://wiki.archlinux.org/index.php/Spectrwm#Statusbar_configuration

**** baraction.sh

***** temperature 

| M4A87TD/USB3 |
|              |
| h77md3h      |
|              |

M4A87TD/USB3
# 

find /sys -name *temp*input*

TB0=$(cat /sys/devices/pci0000:00/0000:00:02.0/0000:05:00.0/hwmon/hwmon0/temp1_input)
TC1=$(cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:2f/ATK0110:00/hwmon/hwmon1/temp1_input)
TC2=$(cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:2f/ATK0110:00/hwmon/hwmon1/temp2_input)
echo -n "|" $(($TB0/1000)) $(($TC1/1000)) $(($TC2/1000)) °C

	# comment for M4A87TD/USB3
	TB0=$(cat /sys/devices/pci0000:00/0000:00:02.0/0000:05:00.0/hwmon/hwmon0/temp1_input)
	TC1=$(cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:2f/ATK0110:00/hwmon/hwmon1/temp1_input)
	TC2=$(cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:2f/ATK0110:00/hwmon/hwmon1/temp2_input)
	echo -n " ("$(($TB0/1000)) $(($TC1/1000)) $(($TC2/1000)) °C")"




h77md3h [2016-02-13 Sat 19:12]


Linux wusb 4.3.3-hardened-r4 #2 SMP Sat Feb 13 16:58:02 CST 2016 x86_64 Intel(R) Celeron(R) CPU G530 @ 2.40GHz GenuineIntel GNU/Linux


find /sys -name *temp*_input*
/sys/devices/virtual/hwmon/hwmon0/temp1_input
/sys/devices/virtual/hwmon/hwmon0/temp2_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input


#!/bin/bash
#baraction.sh for spectrwm status bar


SLEEP_SEC=10  # set bar_delay = 5 in /etc/spectrwm.conf

#loops forever outputting a line every SLEEP_SEC secs
while :; do

	LOAD=$(uptime | sed 's/.*://; s/,//g')
	echo -n "|" $LOAD

	Avail=$(df / -h | awk '$NF ~/^\/$/{print $4}')
	rootfs=$(mount | awk '$3 ~ /^\/$/ {print $1}' | awk 'BEGIN{ FS="[/]"} {print $3}')
	subvolume=$(mount  | awk '$3 ~ /^\/$/ {print $NF}' | sed 's/.*subvol=\/\(.*\))/\1/')


#	rootfs=$(lsblk | awk '$NF ~/^\/$/{print $1}')
	echo -n "|" $rootfs $Avail

	T1=$(cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp1_input)
	T2=$(cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp2_input)
	T3=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input)
	T4=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input)
	T5=$(cat /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input)
	echo -n "|" $(($T1/1000)) $(($T2/1000)) $(($T3/1000)) $(($T4/1000)) $(($T5/1000)) °C


	Avail=$(free -h | awk '$0 ~ /Mem/ {print $NF}')
	Swpfr=$(free -h | awk '$0 ~ /Swap/ {print $NF}')
	echo -n "|" $Avail $Swpfr
	
	ip_dev=$(ip addr | awk '$0 ~ /global/ {print $NF}')
	ip_addr=$(ip addr | awk '$0 ~ /global/ {print $2}' | sed 's/\/..//')
	echo "|" $ip_dev $ip_addr

#	pidssh=$(netstat -tpln | grep ssh | awk '$1 ~ /tcp$/ {print $NF, $4}')

        sleep $SLEEP_SEC
done

***** temperature [2016-02-13 Sat 19:12]


h77md3h 4.3.3-hardened-r4 [2016-01-24 Sun 20:37]

cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp1_input

cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp2_input

find /sys -name hwmon

#!/bin/bash
#baraction.sh for spectrwm status bar


SLEEP_SEC=10  # set bar_delay = 5 in /etc/spectrwm.conf

#loops forever outputting a line every SLEEP_SEC secs
while :; do

	LOAD=$(uptime | sed 's/.*://; s/,//g')
	echo -n "|" $LOAD

	Avail=$(df / -h | awk '$NF ~/^\/$/{print $4}')
	rootfs=$(mount | awk '$3 ~ /^\/$/ {print $1}' | awk 'BEGIN{ FS="[/]"} {print $3}')
	subvolume=$(mount  | awk '$3 ~ /^\/$/ {print $NF}' | sed 's/.*subvol=\/\(.*\))/\1/')


#	rootfs=$(lsblk | awk '$NF ~/^\/$/{print $1}')
	echo -n "|" $rootfs $Avail

	T1=$(cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp1_input)
	T2=$(cat /sys/devices/virtual/hwmon/hwmon0/subsystem/hwmon0/temp2_input)
	echo -n "|" $(($T1/1000)) $(($T2/1000)) °C

	Avail=$(free -h | awk '$0 ~ /Mem/ {print $NF}')
	Swpfr=$(free -h | awk '$0 ~ /Swap/ {print $NF}')
	echo -n "|" $Avail $Swpfr
	
	ip_dev=$(ip addr | awk '$0 ~ /global/ {print $NF}')
	ip_addr=$(ip addr | awk '$0 ~ /global/ {print $2}' | sed 's/\/..//')
	echo "|" $ip_dev $ip_addr

#	pidssh=$(netstat -tpln | grep ssh | awk '$1 ~ /tcp$/ {print $NF, $4}')

        sleep $SLEEP_SEC
done

***** btrfs subvolume

http://www.grymoire.com/Unix/sed.html

#+HEADERS: :results raw
#+BEGIN_SRC sh

  mount  | awk '$3 ~ /^\/$/ {print $NF}' | sed 's/.*subvol=\/\(.*\))/\1/'
# mount  | awk '$3 ~ /^\/$/ {print $NF}' | sed 's/.*subvol=\/\(.*\)/\1/'

# mount | awk '$3 ~ /^\/$/ {print $NF}' # | awk 'BEGIN{ FS="[,]"} {print $NF}'  
# mount | awk '$3 ~ /^\/$/ {print $NF}' # | awk 'BEGIN{ FS="[,]"} {print $NF}'  

#+END_SRC

#+RESULTS:
fs2/snapshot20160210
fs2/snapshot20160210)
(rw,noatime,compress=lzo,noacl,space_cache,autodefrag,inode_cache,subvolid=263,subvol=/fs2/snapshot20160210)
(rw,noatime,compress=lzo,noacl,space_cache,autodefrag,inode_cache,subvolid=263,subvol=/fs2/snapshot20160210)

***** root device

#+HEADERS: :results raw
#+BEGIN_SRC sh

mount | awk '$3 ~ /^\/$/ {print $1}' | awk 'BEGIN{ FS="[/]"} {print $3}'

#  mount #| awk '$3 ~ /^\/$/ {print $1}'   | awk 'BEGIN{ FS="[/]"} {print $3}'
#  mount  | awk '$3 ~ /^\/$/ {print $1}' # | awk 'BEGIN{ FS="[/]"} {print $3}'
#  mount  | awk '$3 ~ /^\/$/ {print $1}'   | awk 'BEGIN{ FS="[/]"} {print $3}'

#+END_SRC

#+RESULTS:
sdb



***** ip addr
	
#	ip_dev=$(ip addr | awk '$0 ~ /global/ {print $NF $2}')
	ip_addr=$(ip addr | awk '$0 ~ /global/ {print $NF, $2}' | sed 's/\/..//')
#	ip_addr=$(ip addr | awk '$0 ~ /global/ {print $2}' | sed 's/\/..//')
	echo -n "" $ip_addr

#	pidssh=$(netstat -tpln | grep ssh | awk '$1 ~ /tcp$/ {print $NF, $4}'); echo "" $pidssh
	pidssh=$(ps -e | grep -w 'ssh$' | awk '{print $1}'); echo " ssh" $pidssh


**** temperature kernel


h77md3h
x86_pkg_temp_thermal 
motherboard temperature

| 4.3.3hardened-r4                             |
|----------------------------------------------|
| Device Drivers                               |
| Generic Thermal sysfs driver                 |
| <M>   X86 package temperature thermal driver |
|                                              | 

| 4.3.3hardened-r4                               |
|------------------------------------------------|
| Device Drivers                                 |
| Hardware Monitoring support                    |
| <M>   Intel Core/Core2/Atom temperature sensor |
|                                                |
**** .spectrwm.conf

cp /etc/spectrwm.conf ~/.spectrwm.conf


# workspace_limit	= 22
  workspace_limit	= 6

# modkey = Mod1
  modkey = Mod4

# program[lock]		= xlock
  program[lock]		= /bin/false

# program[term]		= xterm
  program[term]		= xterm -fg white -bg black

**** libswmhack.so.0.0

find /usr -name libswmhack.so.0.0
/usr/lib64/libswmhack.so.0.0

ERROR: ld.so: object '/usr/local/lib/libswmhack.so.0.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

ls -lha /usr/local/lib

#

cd /usr/local/lib

ln -s /usr/lib64/libswmhack.so.0.0

ls -lha




# bar_action		= baraction.sh
  bar_action		= /home/c5766/baraction.sh  # valid
  bar_action		= ~/baraction.sh            # valid
  bar_action		= baraction.sh              # external app failed: no such file or directory.



*** TightVNC

http://wiki.gentoo.org/wiki/TightVNC

**** just installing the client,

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge --ask --update --newuse net-misc/tightvnc


**** server
USE="server" emerge -uN tightvnc


echo "app-editors/emacs xft" >> /etc/portage/package.use

su

echo "net-misc/tightvnc server" >> /etc/portage/package.use

emerge -uN tightvnc

|    |   tsghcloud |   |
| ip | 10.161.0.97 |   |
|    |             |   |

vncviewer 10.161.0.97




** editors

*** google-chrome


proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge www-client/google-chrome  --autounmask-write

proxychains -f /home/c5766/.proxychains/proxychains.conf \

emerge -pv www-client/google-chrome  


dispatch-conf


emerge www-client/google-chrome  








*** gimp



echo "media-gfx/gimp jpeg jpeg2k pdf png svg tiff" >> /etc/portage/package.use/gimp

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge media-gfx/gimp  


*** emacs

https://wiki.gentoo.org/wiki/GNU_Emacs


**** flag

echo "app-editors/emacs xft X jpeg png svg tiff alsa gif imagemagick sound" >> /etc/portage/package.use/emacs


dispatch-conf


emerge app-editors/emacs  --autounmask-write


USE flag

USE="X acl alsa dbus gif gpm gtk gtk3 inotify jpeg png svg tiff xft xpm zlib

 -Xaw3d (-aqua) -athena -games -gconf -gfile -gnutls -gsettings -gzip-el -hesiod -imagemagick -kerberos -libxml2 -livecd -m17n-lib -motif -pax_kernel (-selinux) -sound -source -toolkit-scroll-bars -wide-int" 0 KiB

nano -w /etc/portage/package.use/emacs

X acl alsa dbus gif gpm gtk gtk3 inotify jpeg png svg tiff xft xpm zlib

**** chinese


(set-fontset-font (frame-parameter nil 'font)
      'han '("Noto Sans TC Thin"))

 (setq face-font-rescale-alist '(("Noto Sans TC Thin" . 1.3)))

no function at [2016-01-14 Thu 11:49]

http://superuser.com/questions/781924/unexpected-result-from-face-font-rescale-alist-in-emacs

;; in .emacs
(defadvice frame-notice-user-settings (before my:rescale-alist)
  (message "Set face-font-rescale-alist")
  (add-to-list 'face-font-rescale-alist
               (cons (font-spec :family "STIXGeneral") 0.95) t))
(ad-activate 'frame-notice-user-settings)

;; in .emacs
(defadvice frame-notice-user-settings (before my:rescale-alist)
  (message "Set face-font-rescale-alist")
  (add-to-list 'face-font-rescale-alist
               (cons (font-spec :family "Noto Sans TC Thin") 1.3) t))
(ad-activate 'frame-notice-user-settings)

;; in .emacs
(defadvice frame-notice-user-settings (before my:rescale-alist)
  (message "Set face-font-rescale-alist")
  (add-to-list 'face-font-rescale-alist
               (cons (font-spec :family "Noto Sans TC Thin") 1.3) t))
  (message "Set face-font-rescale-alist")
  (add-to-list 'face-font-rescale-alist
               (cons (font-spec :family "Noto Sans TC Thin") 1.3) t))
(ad-activate 'frame-notice-user-settings)

**** emacs click url

| step      | C-h v                       |
|-----------+-----------------------------|
| 1         | Browse Url Browser Function |
|           |                             |
| default   | browse-url-default-browser  |
|           |                             |
| change to | browse-url-firefox          |
|           |                             |
|           | [2016-02-18 Thu 16:35]      |
|           | browse-url-chromium         |
|-----------+-----------------------------|
| 2         | Browse Url Firefox Program  |
|           |                             |
| default   | firefox                     |
| change to | firefox-bin                 |
|           |                             |
| 2.1       | Browse Url Chromium Program |
|           |                             |
| default   | chromium                    |
|           |                             |
|           | [2016-02-18 Thu 16:38]      |
|           | google-chrome-stable        |
|           |                             |
|-----------+-----------------------------|
| 3         | org-file-apps               |
|           | Extension: \.x?html?\'      |
|           |                             |
| default   | Use default                 |
| change to | firefox-bin %s              |
|           |                             |
|           | [2016-02-18 Thu 16:40]      |
|           |                             |





*** firefox

emerge -pv firefox

echo "www-client/firefox dbus" > /etc/portage/package.use/firefox

emerge -pv firefox

emerge firefox



*** imagemagick

echo "media-gfx/imagemagick jpeg tiff" > /etc/portage/package.use/imagemagick 

echo "media-gfx/imagemagick jpeg jpeg2k tiff png svg" > /etc/portage/package.use/imagemagick 


emerge -pv media-gfx/imagemagick

emerge media-gfx/imagemagick


*** gthumb


echo "media-gfx/gthumb jpeg tiff" > /etc/portage/package.use/gthumb

emerge -pv media-gfx/gthumb

emerge media-gfx/gthumb --autounmask-write

dispatch-conf

echo " dev-libs/libxml2 -icu" > /etc/portage/package.use/libxml2

emerge -pv dev-libs/libxml2

emerge dev-libs/libxml2


*** pdfshuffler




proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-text/pdfshuffler --autounmask-write

dispatch-conf




proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-text/pdfshuffler


*** libreoffice-bin

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-office/libreoffice-bin  --autounmask-write

dispatch-conf



*** doc docx

**** app-text/docx2txt

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge --ask app-text/docx2txt

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-text/docx2txt --autounmask-write 

dispatch-conf

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge app-text/docx2txt


find / -name docx2txt*
/var/db/pkg/app-text/docx2txt-1.4
/var/db/pkg/app-text/docx2txt-1.4/docx2txt-1.4.ebuild
/usr/bin/docx2txt
/usr/share/doc/docx2txt-1.4
/usr/share/doc/docx2txt-1.4/docx2txt.config.bz2
/usr/portage/distfiles/docx2txt-1.4.tgz
/usr/portage/app-text/docx2txt
/usr/portage/app-text/docx2txt/docx2txt-1.3.ebuild
/usr/portage/app-text/docx2txt/docx2txt-1.4.ebuild
/usr/portage/app-text/docx2txt/files/docx2txt-1.1-paragraph-newline.patch
/usr/portage/app-text/docx2txt/docx2txt-1.2.ebuild
/usr/portage/metadata/md5-cache/app-text/docx2txt-1.3
/usr/portage/metadata/md5-cache/app-text/docx2txt-1.2
/usr/portage/metadata/md5-cache/app-text/docx2txt-1.4


3. Emacs Editor
   ------------

You can add following lines in your ~/.emacs file to view the text content of
a .docx file directly when using emacs.

(add-to-list 'auto-mode-alist '("\\.docx\\'" . docx2txt))

(defun docx2txt ()
  "Run docx2txt on the entire buffer."
  (shell-command-on-region (point-min) (point-max) "docx2txt.pl" t t))

Be warned that with above ~/.emacs code addition, if you happen to save the
buffer/file, it will overwrite the .docx file with the text content.


but docx2txt.pl not available. I remove the .pl and it works. [2015-09-17 Thu 09:57]



**** antiword

proxychains -f /home/c5766/.proxychains/proxychains.conf \
emerge --ask app-text/antiword


**** DONE dotemacs

http://www.emacswiki.org/emacs/AntiWord

(add-to-list 'auto-mode-alist '("\\.doc\\'" . no-word))

    (defun no-word ()
      "Run antiword on the entire buffer."
      (shell-command-on-region (point-min) (point-max) "antiword - " t t))

confirmed effective

**** ms word

|          |         | last   | official                                                     |           |
|          |         | modify | website                                                      |           |
|          | version | year   |                                                              |           |
|          |         |        |                                                              |           |
|----------+---------+--------+--------------------------------------------------------------+-----------|
| antiword |    0.37 | 2005   | http://www.winfield.demon.nl/                                | official  |
|          |         |        |                                                              |           |
|          |         |        | http://archive09.linux.com/articles/113959                   |           |
|          |         |        |                                                              |           |
|          |         |        | http://www.emacswiki.org/emacs-en/AntiWord                   | eamcswiki |
|          |         |        |                                                              |           |
|----------+---------+--------+--------------------------------------------------------------+-----------|
|          |         |        |                                                              |           |
| catdoc   |  0.94.4 | 2005   | http://www.wagner.pp.ru/~vitus/software/catdoc/              | official  |
|          |         |        |                                                              |           |
|          |         |        | http://www.wagner.pp.ru/~vitus/software/catdoc/catdoc.1.html | man       |
|          |         |        |                                                              |           |
|          |         |        |                                                              |           |


man antiword

antiword
      -w width
              In text mode this is the line width in characters. A value of zero puts an entire paragraph on a line, useful when the text is to used as input for another wordprocessor. This value is ignored in PostScript mode.


antiword -w 0 word.doc


catdoc

-w

disables word wrapping. By default catdoc output is splitted into lines not longer than 72 (or number, specified by -m option) characters and paragraphs are separated by blank line. With this option each paragraph is one long line.

catdoc -w  (equal to catdoc -m 0)

-m number

Specifies right margin for text (default 72). -m 0 is equivalent to -w




** app-text/tesseract

echo "app-text/tesseract jpeg png tiff" > /etc/portage/package.use/tesseract 

emerge -pv app-text/tesseract

emerge app-text/tesseract --autounmask-write

dispatch-conf

emerge app-text/tesseract 

*** example

TESSERACT OCR 中文識別嘗試

http://miphol.com/muse/2013/05/tesseract-ocr.html

 
* M4A87TD/USB3, BIOS 1102    12/09/2010 inventory

[2015-05-14 Thu 15:57]

** lspci

 lspci -n
00:00.0 0600: 1002:5957
00:02.0 0604: 1002:5978
00:09.0 0604: 1002:597e
00:0a.0 0604: 1002:597f
00:11.0 0106: 1002:4390 (rev 40)
00:12.0 0c03: 1002:4397
00:12.2 0c03: 1002:4396
00:13.0 0c03: 1002:4397
00:13.2 0c03: 1002:4396
00:14.0 0c05: 1002:4385 (rev 42)
00:14.1 0101: 1002:439c (rev 40)
00:14.2 0403: 1002:4383 (rev 40)
00:14.3 0601: 1002:439d (rev 40)
00:14.4 0604: 1002:4384 (rev 40)
00:14.5 0c03: 1002:4399
00:15.0 0604: 1002:43a0
00:16.0 0c03: 1002:4397
00:16.2 0c03: 1002:4396
00:18.0 0600: 1022:1200
00:18.1 0600: 1022:1201
00:18.2 0600: 1022:1202
00:18.3 0600: 1022:1203
00:18.4 0600: 1022:1204
01:00.0 0200: 10ec:8168 (rev 06)
03:00.0 0c03: 1033:0194 (rev 03)
04:00.0 0101: 197b:2368
05:00.0 0300: 10de:0e22 (rev a1)
05:00.1 0403: 10de:0beb (rev a1)

If you have an ASUS mother board it's fairly easy. If you look under Drivers -> Hardware Monitoring Support right at the bottom of the page there is "ASUS ATK0110" and "STMicroeletronics LIS3* three-axis digital accelerometer". I'm not sure how I found it but the atk0110 seems to work well on my newer M4A87TD EVO board and my old P5Q-E. 

https://forums.gentoo.org/viewtopic-t-813030-highlight-lmsensors.html


** driver

| Driver               | Device                                                    | Vendor                                 |   PCI ID | Works? | Kernel   |
|----------------------+-----------------------------------------------------------+----------------------------------------+----------+--------+----------|
|                      | RX780/RX790 Host Bridge                                   | Advanced Micro Devices, Inc. [AMD/ATI] | 10025957 |        |          |
|                      | RX780/RD790 PCI to PCI bridge (external gfx0 port A)      | Advanced Micro Devices, Inc. [AMD/ATI] | 10025978 |        |          |
|                      | RD790 PCI to PCI bridge (PCI express gpp port E)          | Advanced Micro Devices, Inc. [AMD/ATI] | 1002597e |        |          |
|                      | RD790 PCI to PCI bridge (PCI express gpp port F)          | Advanced Micro Devices, Inc. [AMD/ATI] | 1002597f |        |          |
| ahci                 | SB7x0/SB8x0/SB9x0 SATA Controller [IDE mode]              | Advanced Micro Devices, Inc. [AMD/ATI] | 10024390 | Yes    | v2.6.25- |
|                      | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    | Advanced Micro Devices, Inc. [AMD/ATI] | 10024397 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     | Advanced Micro Devices, Inc. [AMD/ATI] | 10024396 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    | Advanced Micro Devices, Inc. [AMD/ATI] | 10024397 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     | Advanced Micro Devices, Inc. [AMD/ATI] | 10024396 |        |          |
| i2c_piix4,sp5100_tco | SBx00 SMBus Controller                                    | Advanced Micro Devices, Inc. [AMD/ATI] | 10024385 | Yes    | v2.6.25- |
| pata_atiixp          | SB7x0/SB8x0/SB9x0 IDE Controller                          | Advanced Micro Devices, Inc. [AMD/ATI] | 1002439c | Yes    |          |
| snd_hda_intel        | SBx00 Azalia (Intel HDA)                                  | Advanced Micro Devices, Inc. [AMD/ATI] | 10024383 | Yes    | v2.6.25- |
|                      | SB7x0/SB8x0/SB9x0 LPC host controller                     | Advanced Micro Devices, Inc. [AMD/ATI] | 1002439d |        |          |
|                      | SBx00 PCI to PCI Bridge                                   | Advanced Micro Devices, Inc. [AMD/ATI] | 10024384 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB OHCI2 Controller                    | Advanced Micro Devices, Inc. [AMD/ATI] | 10024399 |        |          |
|                      | SB700/SB800/SB900 PCI to PCI bridge (PCIE port 0)         | Advanced Micro Devices, Inc. [AMD/ATI] | 100243a0 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    | Advanced Micro Devices, Inc. [AMD/ATI] | 10024397 |        |          |
|                      | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     | Advanced Micro Devices, Inc. [AMD/ATI] | 10024396 |        |          |
|                      | Family 10h Processor HyperTransport Configuration         | Advanced Micro Devices, Inc. [AMD]     | 10221200 |        |          |
|                      | Family 10h Processor Address Map                          | Advanced Micro Devices, Inc. [AMD]     | 10221201 |        |          |
| amd64_edac_mod       | Family 10h Processor DRAM Controller                      | Advanced Micro Devices, Inc. [AMD]     | 10221202 | Yes    | v3.16.0- |
| k10temp              | Family 10h Processor Miscellaneous Control                | Advanced Micro Devices, Inc. [AMD]     | 10221203 | Yes    | v2.6.33- |
|                      | Family 10h Processor Link Control                         | Advanced Micro Devices, Inc. [AMD]     | 10221204 |        |          |
| r8169                | RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller | Realtek Semiconductor Co., Ltd.        | 10ec8168 | Yes    |          |
|                      | uPD720200 USB 3.0 Host Controller                         | NEC Corporation                        | 10330194 |        |          |
| jmicron              | JMB368 IDE controller                                     | JMicron Technology Corp.               | 197b2368 | Yes    |          |
|                      | GF104 [GeForce GTX 460]                                   | NVIDIA Corporation                     | 10de0e22 |        |          |
|                      | GF104 High Definition Audio Controller                    | NVIDIA Corporation                     | 10de0beb |        |          |
|                      |                                                           |                                        |          |        |          |
|                      |                                                           |                                        |          |        |          |


** cpu

https://en.wikipedia.org/wiki/List_of_AMD_Phenom_microprocessors#Phenom_II_series

Model Number	Step.	Freq.	L2 Cache	L3 Cache	HT	Multi1	Voltage	TDP	Socket	Release Date	Part Number

Phenom II X4 955	

C2	3.2 GHz	4x 512 KB	6 MB	2 GHz	16x	0.850 - 1.400	125 W	AM3	April 2009	HDX955FBK4DGI
C3	3.2 GHz	4x 512 KB	6 MB	2 GHz	16x	0.850 - 1.400	125 W	AM3	November 4, 2009	HDX955FBK4DGM
C3	3.2 GHz	4x 512 KB	6 MB	2 GHz	16x	0.850 - 1.400	95 W	AM3	Q2 2010	HDX955WFK4DGM


cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 2
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 3
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

cat /proc/cpuinfo




** cpu kernel

*** Kernel/Gentoo Kernel Configuration Guide

https://wiki.gentoo.org/wiki/Kernel/Gentoo_Kernel_Configuration_Guide

*** Kernel/Configuration

https://wiki.gentoo.org/wiki/Kernel/Configuration


*** Chapter 7. Configuring a Linux Kernel

http://swift.siphos.be/linux_sea/kernelbuilding.html






** official

https://www.asus.com/tw/Motherboards/M4A87TDUSB3/specifications/


CPU
AMD AM3 Phenom™ II/Athlon™ II/Sempron™ 100 Series 處理器 
支援 AM3 45 nm CPU
支援 CPU 最高至 140 W
AMD Cool 'n' Quiet™ Technology

晶片組
AMD 870/SB850

記憶體
4 x DIMM, Max. 16GB, DDR3 2000(O.C.)/1600/1333/1066 Hz ECC, 非ECC, 無緩衝區 Memory
Dual Channel Memory Architecture
有關記憶體合格廠商清單（QVL）的相關資訊，請參閱 www.asus.com 網站或本使用手冊。
由於作業系統的限制，當安裝記憶體總容量達 4GB 或以上時，WindowsR 32 位元作業系統僅能識別 3GB。如果您要在主機板上安裝 4GB 或更多的記憶體，可安裝 64 位元 Windows 作業系統。
由於 CPU 規格，AMD 100 及 200 系列 CPU 最高支援 DDR3 1066Mhz。藉由華碩的設計，這款主機板最高可支援 DDR3 1333MHz。
支援超低電壓 DDR3 記憶體

系統匯流排
Up to 5.2 GT/s HyperTransport™ 3.0

擴充槽
1 x PCIe 2.0 x16 
1 x PCIe 2.0 x4 
1 x PCIe 2.0 x1 
3 x PCI

資料儲存應用
AMD SB850 controller : 
6 x SATA 6Gb/s埠 (灰), 白色
支援Raid 0, 1, 5, 10
JMicron® JMB368 controller : 
1 x UltraDMA 133/100/66 最多可連接兩部 PATA裝置, 海軍藍

區域網路
Realtek 8111E , 1 x Gigabit LAN Controller(s), 具備 AI NET2功能

音效
VIA VT1818 8 通道 高傳真音效 CODEC
- Supports : 插頭偵測, 多路音頻輸出輸入, 前面板插孔指定功能
Audio Feature :
- Absolute Pitch 192kHz/ 24-bit True BD Lossless Sound
- 華碩雜訊過濾器
- 光纖 S/PDIF 輸出埠位於背板

USB連接埠
NEC® USB 3.0 controller : 
2 x USB 3.0 port(s) (2 位於背板, 藍色)
AMD SB850 controller : 
12 x USB 2.0 port(s) (6 位於背板, 黑色, 6 位於主機板中)

獨家超頻功能
Overclocking Protection :
- ASUS C.P.R.(CPU Parameter Recall)

獨特功能
華碩 Xtreme 設計 :
ASUS Hybrid Processor - TurboV EVO :
- Turbo Unlocker
- TurboV
- CPU Level Up
華碩 EPU :
- EPU 
華碩 Hybrid Switch :
- Core Unlocker
- Turbo Key
華碩獨家功能 :
- MemOK!
- 快速開機
華碩靜音散熱解決方案 :
- 風格獨特的無風扇設計 - 散熱解決方案
- 華碩 Fan Xpert 
華碩 EZ DIY :
- 華碩 O.C. Profile
- 華碩 CrashFree BIOS 3 
- 華碩 EZ Flash 2 
- 華碩 MyLogo 2 
- 多國語言 BIOS

後面板輸出端子
1 x PS/2 鍵盤(紫)
1 x PS/2 滑鼠(綠)
1 x LAN (RJ45) 連接埠
2 x USB 3.0 
6 x USB 2.0 
1 x 光纖 S/PDIF 輸出
3 x 音訊插孔

內建 I/O 連接孔
3 x USB 2.0 接頭支援額外的 6 USB 3.0 連接埠
1 x IDE 接頭
1 x COM 接頭連接埠
6 x SATA 6Gb/s 接頭
1 x CPU 風扇接頭 
1 x 機殼風扇接頭 (3 -pin)
1 x 電源風扇接頭 
1 x S/PDIF 輸出接頭
1 x 24-pin EATX 電源接頭
1 x 4-pin ATX 12V 電源接頭
1 x 前面板音訊接頭 (AAFP)
1 x 系統面板 
1 x MemOK! 按鈕
1 x Core Unlocker 開關
1 x Clear CMOS 跳線

配件
使用者手冊
I/O 擋板
1 x UltraDMA 133/100 纜線
2 x Serial ATA 3.0Gb/s 纜線
1 x Serial ATA 6.0Gb/s 纜線
1 x Q-connector(s) (2 合一) *1

BIOS
8 Mb Flash ROM , SPI, AMI BIOS, PnP, DMI2.0, WfM2.0, SM BIOS 2.5, ACPI 2.0a, Multi-language BIOS, ASUS EZ Flash 2, ASUS CrashFree BIOS 3

管理能力
WfM 2.0,DMI 2.0,WOL by PME,WOR by PME,PXE

支援光碟
Drivers
Anti-virus software (OEM version)
ASUS Utilities 
ASUS Update

主機板尺寸
ATX Form Factor 
12 inch x 8.4 inch ( 30.5 cm x 21.3 cm )

備註
*1: USB, System panel; Retail version only.


* M4A87TD/USB3 gentoo installation

** steps

| steps |                    |
|-------+--------------------|
|    20 | hardware inventory |
|       |                    |
|    22 | lsblk              |
|       |                    |
|    24 | btrfs              |
|       |                    |
|    26 | net card + vga     |
|       |                    |
|-------+--------------------|
|    30 | 2 big files        |
|       |                    |
|    32 | download           |
|       |                    |
|    34 | extract            |
|       |                    |
|       |                    |


** 22 lsblk


[2016-03-28 Mon 16:04]

sda                         8:0    0 279.5G  0 disk 
├─sda1                      8:1    0     2M  0 part 
├─sda2                      8:2    0   122M  0 part 
├─sda3                      8:3    0   488M  0 part 
├─sda4                      8:4    0   8.7G  0 part 
├─sda5                      8:5    0   9.3G  0 part 
└─sda6                      8:6    0 260.9G  0 part 
sdb                         8:16   0 465.8G  0 disk 
└─sdb1                      8:17   0 445.3G  0 part 

** 24 btrfs

mkfs.btrfs -f /dev/sda

mount -o defaults,noatime,noacl,compress=lzo,inode_cache,space_cache,autodefrag /dev/sda /mnt/sda


btrfs subvolume create fs1

btrfs subvolume create fs2


btrfs subvolume create fs3

btrfs subvolume create fs4



** 26 net card + vga

|              | net card                                                  | vga                     |
|--------------+-----------------------------------------------------------+-------------------------|
| M4A87TD/USB3 | RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller | GF104 [GeForce GTX 460] |
| cp6320       | r8169                                                     |                         |


*** r8169

level 1    Device Drivers  --->    
| 2 | 3 | 4 | 5 | location |                                               | default | modification | motherboard |
|---+---+---+---+----------+-----------------------------------------------+---------+--------------+-------------|
| v |   |   |   |          | [*] Network device support  --->              | *       |              |             |
|   |   |   |   |          |                                               |         |              |             |
|   | v |   |   |          | Ethernet driver support                       |         |              |             |
|   |   |   |   |          |                                               |         |              |             |
|   |   | v |   | buttom   | [*]   Realtek devices                         | blank   | *            | cp6320      |
|   |   |   |   |          |                                               |         |              |             |
|   |   | v |   |          | <M>     Realtek 8169 gigabit ethernet support | blank   | M            | cp6320      |
|   |   |   |   |          |                                               |         |              |             |


 
