
* installation


  
* individual package

** imagemagick

echo "media-gfx/imagemagick jpeg tiff" > /etc/portage/package.use/imagemagick 

emerge -pv media-gfx/imagemagick

emerge media-gfx/imagemagick


** gthumb


echo "media-gfx/gthumb jpeg tiff" > /etc/portage/package.use/gthumb

emerge -pv media-gfx/gthumb

emerge media-gfx/gthumb --autounmask-write

dispatch-conf

echo " dev-libs/libxml2 -icu" > /etc/portage/package.use/libxml2

emerge -pv dev-libs/libxml2

emerge dev-libs/libxml2


** parallel

emerge  sys-process/parallel

*** my modification

ls -1 *.tif | parallel convert '{}' '{.}.jpg'

ls -1 *.tif | parallel convert '{}' '{.}.jpg'

ls -1 *.tif | parallel convert '{}' -rotate -90 '{.}-90.jpg'

*** examples

http://superuser.com/questions/71028/batch-converting-png-to-jpg-in-linux

The simplest solution is like most already posted. A simple bash for loop.

for i in *.png ; do convert "$i" "${i%.*}.jpg" ; done
For some reason I tend to avoid loops in bash so here is a more unixy xargs approach, using bash for the name-mangling.

ls -1 *.png | xargs -n 1 bash -c 'convert "$0" "${0%.*}.jpg"'
The one I use. It uses GNU Parallel to run multiple jobs at once, giving you a performance boost. It is installed by default on many systems and is almost definitely in your repo (it is a good program to have around).

ls -1 *.png | parallel convert '{}' '{.}.jpg'
The number of jobs defaults to the number of processes you have. I found better CPU usage using 3 jobs on my dual-core system.

ls -1 *.png | parallel -j 3 convert '{}' '{.}.jpg'
And if you want some stats (an ETA, jobs completed, average time per job...)

ls -1 *.png | parallel --eta convert '{}' '{.}.jpg'
There is also an alternative syntax if you are using GNU Parallel.

parallel convert '{}' '{.}.jpg' ::: *.png
And a similar syntax for some other versions (including debian).

parallel convert '{}' '{.}.jpg' -- *.png


** app-text/tesseract

echo "app-text/tesseract jpeg png tiff" > /etc/portage/package.use/tesseract 

emerge -pv app-text/tesseract

emerge app-text/tesseract --autounmask-write

dispatch-conf

emerge app-text/tesseract 

*** example

TESSERACT OCR 中文識別嘗試

http://miphol.com/muse/2013/05/tesseract-ocr.html



** sys-boot/mbr

emerge sys-boot/mbr

* hardware

** b1 asus

[2015-05-14 Thu 15:57]

*** lspci

 lspci -n
00:00.0 0600: 1002:5957
00:02.0 0604: 1002:5978
00:09.0 0604: 1002:597e
00:0a.0 0604: 1002:597f
00:11.0 0106: 1002:4390 (rev 40)
00:12.0 0c03: 1002:4397
00:12.2 0c03: 1002:4396
00:13.0 0c03: 1002:4397
00:13.2 0c03: 1002:4396
00:14.0 0c05: 1002:4385 (rev 42)
00:14.1 0101: 1002:439c (rev 40)
00:14.2 0403: 1002:4383 (rev 40)
00:14.3 0601: 1002:439d (rev 40)
00:14.4 0604: 1002:4384 (rev 40)
00:14.5 0c03: 1002:4399
00:15.0 0604: 1002:43a0
00:16.0 0c03: 1002:4397
00:16.2 0c03: 1002:4396
00:18.0 0600: 1022:1200
00:18.1 0600: 1022:1201
00:18.2 0600: 1022:1202
00:18.3 0600: 1022:1203
00:18.4 0600: 1022:1204
01:00.0 0200: 10ec:8168 (rev 06)
03:00.0 0c03: 1033:0194 (rev 03)
04:00.0 0101: 197b:2368
05:00.0 0300: 10de:0e22 (rev a1)
05:00.1 0403: 10de:0beb (rev a1)


*** driver

|   PCI ID | Works? | Vendor                                 | Device                                                    | Driver               | Kernel   |
|----------+--------+----------------------------------------+-----------------------------------------------------------+----------------------+----------|
| 10025957 |        | Advanced Micro Devices, Inc. [AMD/ATI] | RX780/RX790 Host Bridge                                   |                      |          |
| 10025978 |        | Advanced Micro Devices, Inc. [AMD/ATI] | RX780/RD790 PCI to PCI bridge (external gfx0 port A)      |                      |          |
| 1002597e |        | Advanced Micro Devices, Inc. [AMD/ATI] | RD790 PCI to PCI bridge (PCI express gpp port E)          |                      |          |
| 1002597f |        | Advanced Micro Devices, Inc. [AMD/ATI] | RD790 PCI to PCI bridge (PCI express gpp port F)          |                      |          |
| 10024390 | Yes    | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 SATA Controller [IDE mode]              | ahci                 | v2.6.25- |
| 10024397 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    |                      |          |
| 10024396 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     |                      |          |
| 10024397 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    |                      |          |
| 10024396 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     |                      |          |
| 10024385 | Yes    | Advanced Micro Devices, Inc. [AMD/ATI] | SBx00 SMBus Controller                                    | i2c_piix4,sp5100_tco | v2.6.25- |
| 1002439c | Yes    | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 IDE Controller                          | pata_atiixp          |          |
| 10024383 | Yes    | Advanced Micro Devices, Inc. [AMD/ATI] | SBx00 Azalia (Intel HDA)                                  | snd_hda_intel        | v2.6.25- |
| 1002439d |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 LPC host controller                     |                      |          |
| 10024384 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SBx00 PCI to PCI Bridge                                   |                      |          |
| 10024399 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB OHCI2 Controller                    |                      |          |
| 100243a0 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB700/SB800/SB900 PCI to PCI bridge (PCIE port 0)         |                      |          |
| 10024397 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB OHCI0 Controller                    |                      |          |
| 10024396 |        | Advanced Micro Devices, Inc. [AMD/ATI] | SB7x0/SB8x0/SB9x0 USB EHCI Controller                     |                      |          |
| 10221200 |        | Advanced Micro Devices, Inc. [AMD]     | Family 10h Processor HyperTransport Configuration         |                      |          |
| 10221201 |        | Advanced Micro Devices, Inc. [AMD]     | Family 10h Processor Address Map                          |                      |          |
| 10221202 | Yes    | Advanced Micro Devices, Inc. [AMD]     | Family 10h Processor DRAM Controller                      | amd64_edac_mod       | v3.16.0- |
| 10221203 | Yes    | Advanced Micro Devices, Inc. [AMD]     | Family 10h Processor Miscellaneous Control                | k10temp              | v2.6.33- |
| 10221204 |        | Advanced Micro Devices, Inc. [AMD]     | Family 10h Processor Link Control                         |                      |          |
| 10ec8168 | Yes    | Realtek Semiconductor Co., Ltd.        | RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller | r8169                |          |
| 10330194 |        | NEC Corporation                        | uPD720200 USB 3.0 Host Controller                         |                      |          |
| 197b2368 | Yes    | JMicron Technology Corp.               | JMB368 IDE controller                                     | jmicron              |          |
| 10de0e22 |        | NVIDIA Corporation                     | GF104 [GeForce GTX 460]                                   |                      |          |
| 10de0beb |        | NVIDIA Corporation                     | GF104 High Definition Audio Controller                    |                      |          |
|          |        |                                        |                                                           |                      |          |
|          |        |                                        |                                                           |                      |          |


*** cpu

cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 2
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor       : 3
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 955 Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 3200.000
cache size      : 512 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rd
tscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misali
gnsse 3dnowprefetch osvw ibs skinit wdt hw_pstate npt lbrv svm_lock nrip_save vmmcall
bugs            : tlb_mmatch apic_c1e fxsave_leak
bogomips        : 6421.71
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

cat /proc/cpuinfo



