* kernel configuration

https://wiki.gentoo.org/wiki/Tmpfs

KERNEL
File systems  --->
     Pseudo filesystems  --->
          [*] Tmpfs virtual memory file system support (former shm fs)
          [ ] Optional drivers


#

mount -t tmpfs tmpfs /MOUNTPOINT


* Portage TMPDIR on tmpfs

https://wiki.gentoo.org/wiki/Portage_TMPDIR_on_tmpfs

FILE /etc/fstabtmpfs fstab example

tmpfs		/var/tmp/portage		tmpfs	size=6g,uid=portage,gid=portage,mode=775,noatime	0 0

tmpfs		/tmp		tmpfs	size=6g,defaults,noatime,nosuid,nodev,noexec,mode=1777	0 0


Where N is in the form of bytes. It can also be suffixed with k, m, or g to respectively have the form of (k)ilobytes, (m)egabytes or (g)igabytes. It can also be suffixed with a % to limit the tmpfs instance to the percentage of current physical RAM, the default being 50% when the parameter is not specified.


http://askubuntu.com/questions/173094/how-can-i-use-ram-storage-for-the-tmp-directory-and-how-to-set-a-maximum-amount



* kernel.org

https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt


* zram

/etc/local.d zram1 for swap

https://wiki.gentoo.org/wiki/Zram#Gentoo.2FOpenRC_init_script


# 

generate 2 files with +x inside /etc/local.d

|       | G |      |
|-------+---+------|
| zram0 | 2 | swap |

** zram.start

#!/bin/bash

modprobe zram num_devices=1

echo lz4 > /sys/block/zram0/comp_algorithm

echo 2G > /sys/block/zram0/disksize 


mkswap /dev/zram0
swapon /dev/zram0 -p 10


** zram.stop

#!/bin/bash

swapoff /dev/zram0

echo 1 > /sys/block/zram0/reset

modprobe -r zram





* zswap

** grub

http://askubuntu.com/questions/361320/how-can-i-enable-zswap

https://help.ubuntu.com/community/Grub2/Setup#A.2BAC8-etc.2BAC8-default.2BAC8-grub

nano /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="rootwait"

GRUB_CMDLINE_LINUX_DEFAULT="rootwait zswap.enabled=1 zswap.compressor=lz4"

GRUB_CMDLINE_LINUX_DEFAULT="zswap.enabled=1 zswap.compressor=lz4"





** [2016-04-23 Sat 19:34]

| 1 | 2 | 3 | 4 | 5 | 4.4.2-hardened                           | default | change to |
|---+---+---+---+---+------------------------------------------+---------+-----------|
| v |   |   |   |   | Processor type and features              |         |           |
|   |   |   |   |   |                                          |         |           |
|   | v |   |   |   | Enable frontswap to cache swap pages     | none    | *         |
|   |   |   |   |   |                                          |         |           |
|   | v |   |   |   | Compressed cache for swap pages          | none    | *         |
|   |   |   |   |   |                                          |         |           |
|   | v |   |   |   | Low density storage for compressed pages | none    | *         |
|   |   |   |   |   |                                          |         |           |
|---+---+---+---+---+------------------------------------------+---------+-----------|
| v |   |   |   |   | Cryptographic API                        |         |           |
|   |   |   |   |   |                                          |         |           |
|   | v |   |   |   | LZ4 compression algorithm                | none    | *         |


** 4.1.7-hardened-r1
     CLOCK: [2016-04-11 Mon 15:04]

cd /usr/src/linux

make defconfig

make menuconfig

make && make modules_install

| 4 items    | kernel variables                                            |
|------------+-------------------------------------------------------------|
|            | Processor type and features                                 |
|            |                                                             |
| FRONTSWAP  | [*] Enable frontswap to cache swap pages if tmem is present |
|            |                                                             |
| ZSWAP      | [*] Compressed cache for swap pages (EXPERIMENTAL)          |
|            |                                                             |
| ZBUD       | <*> Low density storage for compressed pages                |
|            |                                                             |
|------------+-------------------------------------------------------------|
|            | Cryptographic API                                           |
|            |                                                             |
| CRYPTO_LZ4 | <*>   LZ4 compression algorithm                             |


Symbol: CRYPTO_LZ4 [=n]                                                                              │  
  │ Type  : tristate                                                                                     │  
  │ Prompt: LZ4 compression algorithm                                                                    │  
  │   Location:                                                                                          │  
  │ (1) -> Cryptographic API (CRYPTO [=y])                                                               │  
  │   Defined at crypto/Kconfig:1422                                                                     │  
  │   Depends on: CRYPTO [=y]                                                                            │  
  │   Selects: CRYPTO_ALGAPI [=y] && LZ4_COMPRESS [=m] && LZ4_DECOMPRESS [=y]   



If you want to enable zswap permanently, edit the GRUB configuration file to include zswap.enabled=1 at the end of the GRUB_CMDLINE_LINUX_DEFAULT entry.

http://askubuntu.com/questions/361320/how-can-i-enable-zswap

/etc/default/grub 

# Append parameters to the linux kernel command line for non-recovery entries
#GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX_DEFAULT="zswap.enabled=1 zswap.compressor=lz4 rootwait"


zswap.enabled=1 zswap.compressor=lz4 rootwait


KERNELVER=4.1.7 
EXTENSION=20160114-hardened-zswap

cp .config /boot/config-${KERNELVER}-gentoo-gnu${EXTENSION}
cp System.map /boot/System.map-${KERNELVER}-gentoo-gnu${EXTENSION}
cp arch/x86_64/boot/bzImage /boot/kernel-${KERNELVER}-gentoo-gnu${EXTENSION}
grub2-mkconfig -o /boot/grub/grub.cfg
cp -a .config ../${KERNELVER}-${EXTENSION}.config.bk




** reference

https://www.kernel.org/doc/Documentation/vm/zswap.txt
