* David Scott

http://onlinestatbook.com/2/advanced_graphs/q-q_plots.html


* TJCC

** 優秀論文前三名獎金

1. 各組（基轉組/臨床組）前三名：
   第一名: 獎金10萬元、獎狀、獎座/

第二名: 獎金5萬元、獎狀、獎座/

第三名: 獎金3萬元、獎狀、獎座
2. 第四名至第六名：獎金2萬元及獎狀。
3. 第七名至第十名：獎金1萬元及獎狀。



** 論文投稿內容格式：（請依照投稿系統指定鍵入資料）
摘要題目、作者、服務單位均為中英文對照，內文一律為英文。英文篇名每字字首均統一使用大寫。
內文應包含：Purpose、Materials & Methods、Results、Conclusion共四個段落。
字數限制：Purpose、Materials & Methods、Results、Conclusion四個段落總字數上限為350字，超過者無法成功投遞。(在論文內容左側有字數之提醒)


** 論文投稿 2016 1

*** Purpose


*** Materials & Methods


*** Results



*** Conclusion




** 論文投稿 2016 2

Fine-Needle Aspiration of a breast mass is one of the critical step for diagnosis of breast cancer. The diagnosis depends solely upon a labor-intensive process that can be affected by human factors such as fatigue, reader variation and bias. Pathologists must visually examine and grade the specimens through high-powered microscopes.

Performance of Predictive Models for Breast Cancer Diagnosis from digital images of Fine-Needle Aspiration.

Will Robots Replace Doctors, the performance of artificial intelligence in the Diagnosis of Breast Cancer. 

https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/

https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

乳癌

人工智慧在乳癌病理診斷的表現 醫生的飯碗是否會被機器人取代

Will Robots Replace Doctors -- the performance of artificial intelligence in the Diagnosis of Breast Cancer. 

乳腺癌診斷中的表現。
*** Purpose

Google's Deepmind Computer Go program AlphaGo beats the long time World Go Champion Lee Sedol two times in a row on March 10, 2016. Artificial intelligence (AI) is an area of computer science where computers are designed to think and operate much like a human brain. This study evaluate the performance of AI in medicine, especially in the diagnosis of breast cancer.  Fine-needle aspiration (FNA) of a breast mass is the early critical examination of breast cancer. The interpretation of FNA specimen depends solely upon a labor-intensive process that can be affected by human factors such as fatigue, reader variation and bias. We investigate the potential application of AI in the area of breast cancer diagnosis. The performance of 6 predictive models for fine-needle aspiration (FNA) interpretation in breast cancer are compared.


*** Materials & Methods

The Wisconsin Prognostic Breast Cancer (WPBC) data consists cell nucleus features of FNA digital images from 569 instances. 
Ten real-valued features are computed for each cell nucleus: radius (mean of distances from center to points on the perimeter), texture (standard deviation of gray-scale values), perimeter
area, smoothness (local variation in radius lengths), compactness (perimeter^2 / area - 1.0), concavity (severity of concave portions of the contour), concave points (number of concave portions of the contour), symmetry, fractal dimension ("coastline approximation" - 1). The mean, standard error, and "worst" or largest (mean of the three largest values) of these features were computed for each image, resulting in 30 features.  All feature values are recoded with four significant digits. Missing attribute values: none. Class distribution: 357 benign, 212 malignant.

Total 6 predictive models are examined to predict pathologic results, either benign or malignant. The 6 models are: Back Propagation Network (BPN), Decision Tree (DT), Bayesian Network (BN), Support Vector Mathine (SVM), Logistic Regression (LR) and Discriminant Analysis (DA). The primary end points are accuracy, sensitivity and specificity.

*** Results

The optimized ranges of accuracy, sensitivity and specificity of the 6 predictive models are (0.92 - 0.97), (0.83-0.95), and (0.93 - 0.99). The individual optimized (accuracy, sensitivity, specificity) are (BPN 0.97, 0.95, 0.98), (DT 0.92, 0.90, 0.94), (BN 0.94, 0.84, 0.99), (SVM 0.96, 0.90, 0.99), (LR 0.94, 0.92, 0.95), (DA 0.93, 0.84, 0.98). 


*** Conclusion

The accuracy, sensitivity and specificity of the 6 predictive models are encouraging. 


Bayesian Network

中文姓名
	林敬順1, 林榮禾2, 陳昌明 3
英文姓名
	Chin-Shung Lin, Rong-Ho Lin, Chang-Ming Chen
中文服務單位
	振興醫院1, 國立臺北科技大學工業工程與管理系2, 三軍總醫院 放射腫瘤部3
英文服務單位
	Cheng Hsin General Hospital1, Industrial Engineering and Management National Taipei University of Technology2, Radiation Oncology, Tri-Service General Hospital3

 
目的 / Purpose
Google's Deepmind Computer Go program AlphaGo beats the long time World Go Champion Lee Sedol two times in a row on March 10, 2016. Artificial intelligence (AI) is an area of computer science where computers are designed to think and operate much like a human brain. This study evaluate the performance of AI in medicine, especially in the diagnosis of breast cancer. Fine-needle aspiration (FNA) of a breast mass is the early critical examination of breast cancer. The interpretation of FNA specimen depends solely upon a labor-intensive process that can be affected by human factors such as fatigue, reader variation and bias. We investigate the potential application of AI in the area of breast cancer diagnosis. The performance of 6 predictive models for the interpretation of fine-needle aspiration (FNA) in breast cancer are investigated.
方法 / Method
The Wisconsin Prognostic Breast Cancer (WPBC) data consists cell nucleus features of FNA digital images from 569 instances. Ten real-valued features are computed for each cell nucleus: radius, texture, perimeter area, smoothness, compactness, concavity, concave points, symmetry, fractal dimension. The mean, standard error, and "worst" or largest (mean of the three largest values) of these features were computed for each image, resulting in 30 features. All feature values are recoded with four significant digits. Missing attribute values: none. Class distribution: 357 benign, 212 malignant. Total 6 predictive models are examined to predict pathologic results, either benign or malignant. The 6 models are: Back Propagation Network (BPN), Decision Tree (DT), Bayesian Network (BN), Support Vector Mathine (SVM), Logistic Regression (LR) and Discriminant Analysis (DA). The primary end points are accuracy, sensitivity and specificity.
結果 / Results
The optimized ranges of accuracy, sensitivity and specificity of the 6 predictive models are (0.92 - 0.97), (0.83-0.95), and (0.93 - 0.99). The individual optimized (accuracy, sensitivity, specificity) are (BPN 0.97, 0.95, 0.98), (DT 0.92, 0.90, 0.94), (BN 0.94, 0.84, 0.99), (SVM 0.96, 0.90, 0.99), (LR 0.94, 0.92, 0.95), and (DA 0.93, 0.84, 0.98).
結論 / Conclusion
The accuracy, sensitivity and specificity of the 6 predictive models are encouraging. The clinical applications of AI in medicine may decrease human errors, fatigue, bias and escalate quality and efficiency.

中文題目
人工智慧在乳癌病理診斷的表現 醫生的飯碗是否會被機器人取代
英文題目
Will Robots Replace Doctors -- the performance of artificial intelligence in the Diagnosis of Breast Cancer.
關鍵字一
Bayesian Network
關鍵字二
Decision Tree
關鍵字三
fine-needle aspiration

 
投稿類別(主)
 臨床
投稿類別(副)
 Epidemiology, Pathology, and Diagnosis

 
中文姓名
林敬順1, 林榮禾2, 陳昌明 3
英文姓名
Chin-Shung Lin, Rong-Ho Lin, Chang-Ming Chen
中文服務單位
振興醫院1, 國立臺北科技大學 工業工程與管理系2, 三軍總醫院 放射腫瘤部3
英文服務單位
Cheng Hsin General Hospital1, Industrial Engineering and Management National Taipei University of Technology2, Radiation Oncology, Tri-Service General Hospital3

 
目的 / Purpose
Google's Deepmind Computer Go program AlphaGo beats the long time World Go Champion Lee Sedol two times in a row on March 10, 2016. Artificial intelligence (AI) is an area of computer science where computers are designed to think and operate much like a human brain. This study evaluate the performance of AI in medicine, especially in the diagnosis of breast cancer. Fine-needle aspiration (FNA) of a breast mass is the early critical examination of breast cancer. The interpretation of FNA specimen depends solely upon a labor-intensive process that can be affected by human factors such as fatigue, reader variation and bias. We investigate the potential application of AI in the area of breast cancer diagnosis. The performance of 6 predictive models for the interpretation of fine-needle aspiration (FNA) in breast cancer are investigated.
方法 / Method
The Wisconsin Prognostic Breast Cancer (WPBC) data consists cell nucleus features of FNA digital images from 569 instances. Ten real-valued features are computed for each cell nucleus: radius, texture, perimeter area, smoothness, compactness, concavity, concave points, symmetry, fractal dimension. The mean, standard error, and "worst" or largest (mean of the three largest values) of these features were computed for each image, resulting in 30 features. All feature values are recoded with four significant digits. Missing attribute values: none. Class distribution: 357 benign, 212 malignant. Total 6 predictive models are examined to predict pathologic results, either benign or malignant. The 6 models are: Back Propagation Network (BPN), Decision Tree (DT), Bayesian Network (BN), Support Vector Mathine (SVM), Logistic Regression (LR) and Discriminant Analysis (DA). The primary end points are accuracy, sensitivity and specificity.
結果 / Results
The optimized ranges of accuracy, sensitivity and specificity of the 6 predictive models are (0.92 - 0.97), (0.83-0.95), and (0.93 - 0.99). The individual optimized (accuracy, sensitivity, specificity) are (BPN 0.97, 0.95, 0.98), (DT 0.92, 0.90, 0.94), (BN 0.94, 0.84, 0.99), (SVM 0.96, 0.90, 0.99), (LR 0.94, 0.92, 0.95), and (DA 0.93, 0.84, 0.98).
結論 / Conclusion
The accuracy, sensitivity and specificity of the 6 predictive models are encouraging. The clinical applications of AI in medicine may decrease human errors, fatigue, bias and escalate quality and efficiency.


B121665594


0939-175579

一直出現  sql comment fail sqlPaper1 無法完成投稿
 	

關於我們
年會議程
會場資訊
論文競賽
贊助廠商
歷屆年會
聯絡我們
 		 	
 	
  首頁 > 論文競賽 > 線上投搞 > 新增論文投稿
 	 
 	
 

修改個人資訊

已投稿論文

登出
 

 

 

 

 

 

在了解並同意本次徵稿競賽各項規定後，進行投稿動作，帳號申請者須同為該篇論文之第一作者或通訊作者。 (您投遞的論文若有需要修改或作者排列之異動，請以當初申請帳號人 (第一作者或通訊作者) 登錄線上投稿系統，於截稿日前均可自行修改。)
作者資訊論文內容預覽與送出
 
中文題目
人工智慧在乳癌病理診斷的表現 醫生的飯碗是否會被機器人取代
英文題目
Will Robots Replace Doctors -- the performance of artificial intelligence in the Diagnosis of Breast Cancer
關鍵字一
Bayesian Network
關鍵字二
Decision Tree
關鍵字三
Logistic Regression

 
投稿類別(主)
 臨床
投稿類別(副)
 Epidemiology, Pathology, and Diagnosis

 
中文姓名
林敬順1, 林榮禾2, 陳昌明 3
英文姓名
Chin-Shung Lin, Rong-Ho Lin, Chang-Ming Chen
中文服務單位
振興醫院1, 國立臺北科技大學 工業工程與管理系2, 三軍總醫院 放射腫瘤部3
英文服務單位
Cheng Hsin General Hospital1, Industrial Engineering and Management, National Taipei University of Technology2, Radiation Oncology, Tri-Service General Hospital3

 
目的 / Purpose
Google's Deepmind Computer Go program AlphaGo beats the long time World Go Champion Lee Sedol two times in a row on March 10, 2016. Artificial intelligence (AI) is an area of computer science where computers are designed to think and operate much like a human brain. This study evaluate the performance of AI in medicine, especially in the diagnosis of breast cancer. Fine-needle aspiration (FNA) of a breast mass is the early critical examination of breast cancer. The interpretation of FNA specimen depends solely upon a labor-intensive process that can be affected by human factors such as fatigue, reader variation and bias. We investigate the potential application of AI in the area of breast cancer diagnosis. The performance of 6 predictive models for the interpretation of fine-needle aspiration (FNA) in breast cancer are investigated.
方法 / Method
The Wisconsin Prognostic Breast Cancer (WPBC) data consists cell nucleus features of FNA digital images from 569 instances. Ten real-valued features are computed for each cell nucleus: radius, texture, perimeter area, smoothness, compactness, concavity, concave points, symmetry, fractal dimension. The mean, standard error, and "worst" or largest (mean of the three largest values) of these features were computed for each image, resulting in 30 features. All feature values are recoded with four significant digits. Missing attribute values: none. Class distribution: 357 benign, 212 malignant. Total 6 predictive models are examined to predict pathologic results, either benign or malignant. The 6 models are: Back Propagation Network (BPN), Decision Tree (DT), Bayesian Network (BN), Support Vector Mathine (SVM), Logistic Regression (LR) and Discriminant Analysis (DA). The primary end points are accuracy, sensitivity and specificity.
結果 / Results
The optimized ranges of accuracy, sensitivity and specificity of the 6 predictive models are (0.92 - 0.97), (0.83-0.95), and (0.93 - 0.99). The individual optimized (accuracy, sensitivity, specificity) are (BPN 0.97, 0.95, 0.98), (DT 0.92, 0.90, 0.94), (BN 0.94, 0.84, 0.99), (SVM 0.96, 0.90, 0.99), (LR 0.94, 0.92, 0.95), and (DA 0.93, 0.84, 0.98).
結論 / Conclusion
The accuracy, sensitivity and specificity of the 6 predictive models are encouraging. The clinical applications of AI in medicine may decrease human errors, fatigue, bias and escalate quality and efficiency.


 	
Submit
Submit	
Submit


第二十一屆台灣癌症聯合學術年會籌備會秘書處             聯絡人: 王偉竹 秘書
    電話: 02-2523-9118          傳真: 02-2523-8870      	地址: 10457 台北市中山區吉林路24號6樓      	    E-Mail: bcst@ms46.hinet.net	 
CopyRight @ 2016 Taiwan Joint Cancer Conference All Rights Reserved.	Notice: Undefined index: ContactPhone in F:\Website\TJCC21\footer.php on line 70
** 論文投稿 2016 1

*** Purpose


*** Materials & Methods


*** Results



*** Conclusion




* 癌症登記

http://tcr.cph.ntu.edu.tw/main.php?Page=A5

99年以後之年報，請至國民健康署網站下載

http://www.hpa.gov.tw/BHPNet/Web/Stat/Statistics.aspx


** 年度報告

101年癌症登記年報.pdf

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201504290001


100年癌症登記年報.zip

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201404160001


** text extract

 53,553  26  61  55  85  178  219  304  714 1,257 2,324 3,741 5,321  6,458 6,816 5,320 6,309 5,800 5,047 3,518
 43,141  21  85  50  67  133  217  447  981 1,693 2,732 4,171 4,859  5,337 5,019 3,805 4,224 3,858 3,031 2,411
 96,694  47  146  105  152  311 436 751 1,695 2,950 5,056 7,912 10,180 11,795 11,835 9,125 10,533 9,658 8,078 5,929



** 解壓縮zip檔，產生亂碼

emerge app-arch/p7zip

emerge app-text/convmv


http://www.ubuntu-tw.net/modules/newbb/viewtopic.php?topic_id=91908&forum=7

[分享] 解壓縮zip檔，產生亂碼，如何解決的心得

下載範例檔案

LC_ALL=C 7z x Open_Data.zip 

convmv -f BIG5 -t UTF-8 -r Open_Data

convmv -f BIG5 -t UTF-8 -r Open_Data --notest

convmv -f BIG5 -t UTF-8 -r test

convmv -f BIG5 -t UTF-8 -r test --notest


LC_ALL=C 7z x 100年癌症登記年報.zip

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf --notest



* diigo

** outliner

| library | outliners |   |   |
|         |           |   |   |


What can you do with Outliner?
Organize what you have collected - links, notes, quotes, images, along with your own thoughts
Take meeting notes and arrange them efficiently
Organize quotes for your writing projects
