* reference

** David Scott

http://onlinestatbook.com/2/advanced_graphs/q-q_plots.html


** Understanding Q-Q Plots

http://data.library.virginia.edu/understanding-q-q-plots/


** Math 141 - Quantile-Quantile Plots

http://people.reed.edu/~jones/Courses/P14.pdf


** Exploratory Data Analysis: Quantile-Quantile Plots for New York’s Ozone Pollution Data

https://chemicalstatistician.wordpress.com/2013/09/22/exploratory-data-analysis-quantile-quantile-plots-for-new-yorks-ozone-pollution-data/


** R Source Code Blocks in Org Mode

http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-R.html


** 大腸直腸癌篩檢："有做有保庇”

*** my summary

台灣地區零至第四期大腸直腸癌的五年存活率分別為85.5、81.3、71.3、59.1及11.4%

2012年的統計資料顯示該年因篩檢所偵測到的大腸癌有60.1%為零期至二期的癌症，未接受篩檢族群所診斷的大腸癌僅有31.6%為零期至二期

2004年至2009年接受篩檢個案其大腸直腸癌死亡率相較於從未接受篩檢族群，在平均追蹤3.1年之下足足相差了10%之多



*** default


http://www.hpa.gov.tw/Bhpnet/Web/HealthTopic/TopicArticle.aspx?No=201507130001&parentid=200802140005


大腸直腸癌篩檢："有做有保庇”
近日看到關於質疑我國大腸直腸癌篩檢政策的投書，由於投書者為臨床從業人員並活躍於網路，因此對於其投書內容，建議仍應有完整依據，否則易有斷章取義之憾。該文中指出”在2012年時，約有103萬人接受糞便潛血檢查，約略佔該年齡層19％，只找出2096名大腸癌患者，這樣的人數只佔了當年度全部大腸癌患者約14％。也就是說，未進行篩檢的81％的人口，卻佔了86％大腸癌病患。全國花費了這麼多人力物力，耗費了這麼多健保資源，其效果卻是如此這般，值得憂慮。”筆者多年從事大腸癌篩檢與品質分析工作，為避免上述文章誤導民眾誤，以下就科學實證與臨床實務加以說明。


根據我國衛生統計，台灣地區零至第四期大腸直腸癌的五年存活率分別為85.5、81.3、71.3、59.1及11.4%，而根據國民健康署2012年的統計資料顯示該年因篩檢所偵測到的大腸癌有60.1%為零期至二期的癌症，加上癌前病變更可高達89.2%，相較於未接受篩檢族群所診斷的大腸癌僅有31.6%為零期至二期，足足相差有28.6-57.3%之多。國民健康署近期呈現2004年至2009年接受篩檢個案其大腸直腸癌死亡率相較於從未接受篩檢族群，在平均追蹤3.1年之下足足相差了10%之多，預期在更長的追蹤之下差異會更大，而整個人口裡接受過大腸直腸癌篩檢的民眾比例提升，不僅僅這個死亡率下降的幅度會更大，整個台灣地區大腸直腸癌死亡率的下降也指日可待。

文中提到19%的篩檢率可能是不了解篩檢間隔所致。我國篩檢間隔為兩年，只要兩年內接受過糞便潛血檢查篩檢即計算為已接受篩檢個案。據悉2012年篩檢率的統計數字為36.7%，2014年更提升到40.7%(約為該文所提到19%的兩倍)。而篩檢所耗費的人力物力，未來將可以為健保省下極為可觀的資源，反而是在為珍貴的醫療資源省錢。光是減少第三與第四期個案，所省下的化學治療、標靶治療以及處理各項併發症或緊急住院的費用，如再加上家屬因照顧病患所損失的工作時間與其他直接間接成本，豈是篩檢所使用的資源所能相提並論？具體來說，台灣的大腸直腸癌篩檢每發出一千支糞便採便管(一支成本不到台幣100元)，只有70-80位糞便檢查呈現陽性需要接受大腸鏡檢(健保價2250元)，但卻可以找到兩個至三個大腸癌個案，相較於等到這兩三位民眾有臨床症狀才被診斷所花費的各項醫療資源與社會成本，甚至賠上性命，撥指一算划不划算一目了然，實不需贅言。這個部分在國外眾多的相關決策分析研究已充分證實大腸直腸癌篩檢實為所有癌症的篩檢裡最為符合成本效益，甚至可以為廣大納稅人省錢的一種篩檢政策。再者，國外過去以化學法糞便潛血檢查的大腸直腸癌篩檢臨床試驗(化學法比我國目前所使用之免疫法敏感度低)，均已證實大腸直腸癌篩檢可以有效降低其死亡率，因此在台灣這樣大腸直腸癌高發生率地區，對於是否要進行篩檢乙事，幾無爭論，目前的首要之務乃如何提高篩檢率。當篩檢率提高到歐美的60%甚至70%以上，屆時將不會有那麼多進行期或末期個案，死於大腸直腸癌的個案也會更加減少，不是如該文所提到” 耗費了這麼多健保資源，其效果卻是如此這般”，因為某些“效果”是需要時間才觀察得到的。此外，要提升篩檢率並非一蹴可幾，除民眾觀念需要改變之外，臨床從業人員的提醒是促使民眾接受篩檢最重要的動力，這個不僅僅在國內外的研究也已經被充分證實，而過去包括台灣在內的亞太地區國家所做的調查也顯示醫師的建議乃民眾願意接受篩檢最重要的因素。

在全國公衛同仁與臨床醫護人員的努力之下，台灣已然走在大腸直腸癌防治的正確道路上，實無走回頭路的道理。我們也必須強調的是醫療相關專業同仁必須了解大腸直腸癌篩檢是根據嚴謹的科學證據所進行的，推展的過程可以討論如何可以做得更好或更有效率的運用有限的資源，然它可以有效降低大腸直腸癌的死亡率是不爭的事實，我們必須鄭重告訴民眾:大腸直腸癌篩檢是”有做有保庇”的。



邱瀚模醫師 /台大醫院內科主治醫師、台大醫學院內科臨床副教授、台灣消化系醫學會副秘書長




** 大腸癌防治概況

*** my summary

93年起，開始推動50-69歲大腸癌篩檢服務

102年6月起將篩檢年齡調查為50-74歲

103年50-69歲民眾近2年曾接受糞便潛血檢查比率達40.7％。



*** default

http://www.hpa.gov.tw/Bhpnet/Web/HealthTopic/TopicArticle.aspx?No=200907210002&parentid=200802140005

大腸癌防治概況
一、大腸癌流行病學

在台灣地區，大腸癌發生、死亡人數，每年呈快速增加的趨勢，是所有癌症發生及死亡的第三位。根據癌症登記統計顯示，大腸癌發生人數從84年的4,217人，標準化發生率為每10萬人口22.9人，95年發生人數首次超越肝癌，成為我國癌症發生人數最多的癌症，發生人數已超過12,000人，101年標準化發生率為每10萬人口45.1人，標準化發生率上升97%。而死亡人數從84年的2,469人，標準化死亡率為每10萬人口13.3人，102年已增至5,265人，標準化死亡率為每10萬人口15.3人，標準化死亡率上升15%（如附表）。 

二、大腸癌防治政策

大腸癌早期並無症狀，但可以藉由定期接受篩檢而早期發現早期治療，為治癒率很高的癌症。根據統計，早期的大腸癌如果妥善治療，存活率高達90％以上。大腸癌主要是由大腸內的腺瘤瘜肉癌化所造成，因此，如能早期發現腺瘤瘜肉予以切除，可以減少大腸癌的發生。 據歐美國家經驗，每一至二年糞便潛血篩檢約可下降18％至33％的大腸癌死亡率。因此，本署自93年起，開始推動50-69歲大腸癌篩檢服務，並自99年起納入預防保健服務項目，正式於全國推行，於102年6月起將篩檢年齡調查為50-74歲。依據本署資料統計，103年50-69歲民眾近2年曾接受糞便潛血檢查比率達40.7％。 糞便潛血檢查（FOBT）是檢查糞便中是否有血，目前糞便潛血檢查是用免疫法，不需飲食限制，因此相當簡單方便，但糞便潛血檢查並非百分之百，所以當有任何異狀時，仍應找專科醫師做必要檢查。如果糞便潛血檢查呈陽性時，應進一步接受大腸鏡檢查，其好處是檢查過程如有發現病兆或瘜肉時，可以直接取樣做切片或是將它切除。 另，國人飲食攝取過多紅肉及缺乏運動，是大腸癌發生快速攀升的主要原因；研究指出，飲食中蔬菜水果的攝取可以降低大腸癌的發生，而脂肪、紅肉等攝取過多則可能增加大腸癌的發生。因此，要預防大腸癌的發生，除要多攝食蔬果等高纖維飲食與規律運動外，50-74歲民眾每2年至少應有1次糞便潛血檢驗(IFOBT)，以早期發現大腸癌病變，以早期診治。
 
三、大腸癌防治宣導重點

要如何預防並早期發現大腸癌？ 
1. 養成良好飲食習慣，多吃蔬菜水果，少吃肉類及高油脂食物。
2. 養成每天運動習慣。 
3. 養成定期篩檢的習慣。 大腸癌多發生在50歲以後，所以50歲以上民眾應每1~2年接受糞便潛血檢查，但是有個人或家族瘜肉症或大腸癌病史的民眾，建議直接接受全大腸鏡檢查，檢查年齡也要提早。

四、政府補助哪些結直腸癌篩檢服務

政府目前補助50-74歲民眾每2年一次免疫法定量糞便潛血檢查；可以到全省各地健保特約醫療院所辦理，若有問題可洽詢各地衛生局（所）或健康服務中心。



附件檔案：
￼ 大腸癌歷年發生率及死亡率.doc  ￼ (檔案大小:50 KB 下載次數：7074)
￼ 大腸癌歷年發生率及死亡率.odt  ￼ (檔案大小:11 KB 下載次數：363)



** 衛生福利部公布101年新發生癌症人數及排名 不良生活習慣是罹癌禍因	

*** my summary

|       | 大腸癌發生人數 | 大腸癌篩檢人數 | 篩檢發生大腸癌人數 | 大腸癌人數/篩檢 | 篩檢率 |
| age   |                |          50-69 |                    |                 |        |
|-------+----------------+----------------+--------------------+-----------------+--------|
| 101年 |          14965 |        1120000 |               2001 |         0.00178 |  0.367 |
|       |                |                |                    |                 |        |
| 100年 |      14965-878 | 1120000-337104 |           2001-201 |                 |        |
|       |          14087 |         782896 |               1800 |         0.00230 |        |
|       |                |                |                    |                 |        |


*** default

http://www.hpa.gov.tw/BHPNet/Web/News/News.aspx?No=201504140001


癌症時鐘再度快轉 每5分鐘26秒就有1人罹癌
由於高齡化、生活型態改變、肥胖人口增加及癌症篩檢的推廣，使得台灣癌症發生人數仍持續在增加，根據國民健康署最新出爐的癌症登記報告，101年癌症新發人數為9萬6,694人，發生年齡中位數與100年同為62歲，但發生人數卻較100年增加4,012人，顯示癌症時鐘持續快轉，101年每5分鐘26秒就有1人罹癌，比前一年快了14秒。從粗發生率資料來看，國人每10萬人中約有415人被診斷為癌症，即每233位國人就有1人罹癌。


「六分鐘 護一生」奏效，子宮頸癌首度脫離10大排名
就發生率看來，101年癌症標準化發生率為每10萬人口300人，較100年每10萬人口增加4.9人；在發生人數最多的前10大癌症中，除了肝癌及胃癌外，其他癌別標準化發生率皆上升。肝癌及胃癌標準化發生率已三度呈現下降情形，其中肝癌較100年每10萬人口減少0.8人，推測原因應該與政府長期推動肝炎防治，並針對B肝帶原者或C肝感染者予以後續追蹤管理已產生效應。


另，自84年起，由於政府提供婦女免費子宮頸抹片篩檢，子宮頸癌標準化發生率已長期呈現下降趨勢，現在子宮頸癌標準化發生率更首度脫離了10大癌症發生排行之列，顯示國家篩檢政策奏效。


大腸癌七度居冠，肺癌緊追在後
101年發生人數最多的10大癌症排名，依序為大腸癌，肺癌，肝癌，乳癌，口腔癌(含口咽下咽)，攝護腺癌，胃癌，皮膚癌，甲狀腺癌，食道癌。
其中大腸癌發生人數七度居冠，共1萬4,965人罹癌，較100年發生人數增加878人（增加6％），蟬聯發生人數增加最多的癌症。分析大腸癌發生原因，101年大腸癌篩檢人數112萬人，較100年大腸癌篩檢人數增加約33萬7,104人接受篩檢，101年經由大腸癌篩檢發現2,001位大腸癌病人，較100年大腸癌篩檢多發現約201位大腸癌病人，篩檢人數大幅增加致使透過篩檢發現的癌前病變及癌症個案人數隨之增加。


發生人數第二名是肺癌；101年共計1萬1,692人發現罹癌，較100年發生人數增加633人（增加6％）。主要增加人數在女性，較100年女性肺癌增加499人（增加12％）；其中女性早期（0-1期）個案佔21.6％，較100年增加247人（增加35.1％）。依國際實證，吸菸和二手菸乃是導致肺癌發生的主要危險因子，雖然政府於86年9月開始實施菸害防制法後，國人吸菸率已大幅下降，但依過去各國數據吸菸率下降20年，及戒菸20年後肺癌發生率及死亡率才會下降。需特別提醒二手菸暴露問題對肺癌所造成的影響也不容小覷，特別是家庭二手菸的暴露，根據國民健康署調查資料顯示，我國女性家庭二手菸暴露率在98年曾一度從97年的26.3％降至17.8％，但其後又上升到103年28.5%。長期暴露在二手菸下，不僅會造成如氣喘、支氣管炎和肺氣腫的胸腔問題和心臟病外，還會增加罹患肺癌的危險(資料來源：本署菸害防制網)。


而以標準化發生率來看，每10萬人口中有300人罹癌，其中男性標準化發生率為每10萬人口341.4人，女性標準化發生率則為每10萬人口263.3人；男性發生率為女性的1.3倍。


無症狀就要作篩檢，早期癌無所遁形
「嘸症頭為什麼要檢查?」這是民眾對癌症常見的迷思之一。一般民眾常等到有明顯症狀才就醫，通常都為時已晚。根據資料分析顯示，子宮頸癌，乳癌，口腔癌及大腸癌經由篩檢發現的個案以早期的病例為主，分別為子宮頸癌90.6%（若含癌前病變則為97.3％），乳癌85.3%，口腔癌34.5%（若含癌前病變則為74.1％）及大腸癌60.1%（若含癌前病變則為89.2％）；而前述癌症早期個案的5年存活率皆達7成以上，分別子宮頸癌88.2～96.9％，乳癌89.1～97.7％，口腔癌76.7～77.4％及大腸癌85.5～81.3％，存活率明顯高於晚期個案。癌前病變更是可以經由簡單治療，進而預防癌症發生。另外在肝癌防治方面，由於B型肝炎及C型肝炎患者透過追蹤、治療，可降低3~6成肝癌發生，故國民健康署與健保署合作，提供由健保給付B型肝炎及C型肝炎患者之定期超音波檢查與抽血以篩檢肝癌，以及抗病毒治療，以預防肝癌及肝硬化。肺癌部分現在有研究發現低劑量電腦斷層掃瞄可降低重度吸菸者之肺癌死亡率，然偽陽性狀況甚多，正與專業團隊合作，測試適合國人之可能篩檢模式。至於大腸癌、子宮頸癌及口腔癌經由篩檢發現，一年找出近4萬名癌前病變，經簡單治療就可預防其轉變成癌症，所以提醒民眾務必定期接受癌症篩檢。


不良生活習慣是癌症的禍因
世界衛生組織指出，菸、酒、不健康飲食、缺乏身體活動及肥胖等主要危險因子，佔癌症死因的30％。佔國人罹癌排行榜加總6成左右的大腸癌、肝癌、肺癌、乳癌及口腔癌等五種癌症，都與前述致癌因子有關。如：肺癌的發生受到吸菸與二手菸的影響甚大，口腔癌及食道癌與抽菸、喝酒、嚼檳榔息息相關，而肥胖、不健康飲食及缺乏運動等致癌因子則是大腸癌及女性乳癌發生率居高不下的主要原因。


資料分析顯示，國人在肉類及油脂性食物的可獲量都高過其他亞洲國家，國人普遍存在「無肉不歡」、「靠吃減壓」等錯誤飲食觀念，這樣的飲食習慣對國人的肥胖及罹癌多少都會造成影響。世界衛生組織指出，肥胖較健康體重者罹患乳癌、子宮內膜癌、結直腸癌等癌症的相對危險性介於1至2倍之間。我國癌症登記分析資料也顯示過重及肥胖者相較於體位正常及過輕者容易罹患子宮體癌、女性乳癌、攝護腺癌、甲狀腺癌及肝癌等癌症；其中過重及肥胖者子宮體癌發生率及乳癌發生率分別為體位正常及過輕者的2.9倍及1.6倍。


除了蔬果攝取不足、不健康飲食外，缺乏運動亦是導致大腸癌及乳癌發生的原因。世界衛生組織於2009年指出，約21-25％乳癌及大腸癌，可歸因於身體活動不足。然而依據2013年運動城市調查資料顯示，國人男女缺乏運動的比率分別高達70.7％及83.4％；相較於OECD國家，國人男、女性缺乏運動的比率排名皆居冠。


防癌做得到，健康活到老
台灣癌症標準化發生率與OECD國家比較排名第23高，但死亡率卻排名第10高，高過許多先進國家，顯示我們在癌症防治的工作仍需持續努力。世界衛生組織表示，30％以上的癌症死亡是可以避免的。衛生福利部國民健康署邱淑媞署長大聲疾呼，防癌工作迫在眉睫，全國應該總動員，不分政府及民間單位一起加入抗癌行列，相信「防癌做得到」，只要「預防」與「篩檢」雙管齊下就可以達到最佳防癌效果。
附件檔案：	國健署新聞稿附件1040414.pdf ￼ (檔案大小：590 KB 下載次數：1847)
更新日期：104年04月21日
點擊次數：15687





* TJCC

** 優秀論文前三名獎金

1. 各組（基轉組/臨床組）前三名：
   第一名: 獎金10萬元、獎狀、獎座/

第二名: 獎金5萬元、獎狀、獎座/

第三名: 獎金3萬元、獎狀、獎座
2. 第四名至第六名：獎金2萬元及獎狀。
3. 第七名至第十名：獎金1萬元及獎狀。



** 論文投稿內容格式：（請依照投稿系統指定鍵入資料）
摘要題目、作者、服務單位均為中英文對照，內文一律為英文。英文篇名每字字首均統一使用大寫。
內文應包含：Purpose、Materials & Methods、Results、Conclusion共四個段落。
字數限制：Purpose、Materials & Methods、Results、Conclusion四個段落總字數上限為350字，超過者無法成功投遞。(在論文內容左側有字數之提醒)


** 論文投稿 2016 1

*** Purpose


*** Materials & Methods


*** Results



*** Conclusion




** 論文投稿 2016 1

*** Purpose


*** Materials & Methods


*** Results



*** Conclusion




* 癌症登記

http://tcr.cph.ntu.edu.tw/main.php?Page=A5

99年以後之年報，請至國民健康署網站下載

http://www.hpa.gov.tw/BHPNet/Web/Stat/Statistics.aspx


** 年度報告

101年癌症登記年報.pdf

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201504290001


100年癌症登記年報.zip

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201404160001


** text extract

 53,553  26  61  55  85  178  219  304  714 1,257 2,324 3,741 5,321  6,458 6,816 5,320 6,309 5,800 5,047 3,518
 43,141  21  85  50  67  133  217  447  981 1,693 2,732 4,171 4,859  5,337 5,019 3,805 4,224 3,858 3,031 2,411
 96,694  47  146  105  152  311 436 751 1,695 2,950 5,056 7,912 10,180 11,795 11,835 9,125 10,533 9,658 8,078 5,929



** 解壓縮zip檔，產生亂碼

emerge app-arch/p7zip

emerge app-text/convmv


http://www.ubuntu-tw.net/modules/newbb/viewtopic.php?topic_id=91908&forum=7

[分享] 解壓縮zip檔，產生亂碼，如何解決的心得

下載範例檔案

LC_ALL=C 7z x Open_Data.zip 

convmv -f BIG5 -t UTF-8 -r Open_Data

convmv -f BIG5 -t UTF-8 -r Open_Data --notest

convmv -f BIG5 -t UTF-8 -r test

convmv -f BIG5 -t UTF-8 -r test --notest


LC_ALL=C 7z x 100年癌症登記年報.zip

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf --notest



* Replicate each row of data.frame and specify the number of replications for each row

http://stackoverflow.com/questions/2894775/replicate-each-row-of-data-frame-and-specify-the-number-of-replications-for-each

df <- data.frame(var1=c('a', 'b', 'c'), var2=c('d', 'e', 'f'), freq=1:3)

In other words, go from this:

df
  var1 var2 freq
1    a    d    1
2    b    e    2
3    c    f    3

To this:

df.expanded
  var1 var2
1    a    d
2    b    e
3    b    e
4    c    f
5    c    f
6    c    f

* Working with categorical data with R and the vcd and vcdExtra packages


http://www.datavis.ca/courses/VCD/vcd-tutorial.pdf


* diigo

** outliner

| library | outliners |   |   |
|         |           |   |   |


What can you do with Outliner?
Organize what you have collected - links, notes, quotes, images, along with your own thoughts
Take meeting notes and arrange them efficiently
Organize quotes for your writing projects


