* David Scott

http://onlinestatbook.com/2/advanced_graphs/q-q_plots.html


* TJCC

** 優秀論文前三名獎金

1. 各組（基轉組/臨床組）前三名：
   第一名: 獎金10萬元、獎狀、獎座/

第二名: 獎金5萬元、獎狀、獎座/

第三名: 獎金3萬元、獎狀、獎座
2. 第四名至第六名：獎金2萬元及獎狀。
3. 第七名至第十名：獎金1萬元及獎狀。



** 論文投稿內容格式：（請依照投稿系統指定鍵入資料）
摘要題目、作者、服務單位均為中英文對照，內文一律為英文。英文篇名每字字首均統一使用大寫。
內文應包含：Purpose、Materials & Methods、Results、Conclusion共四個段落。
字數限制：Purpose、Materials & Methods、Results、Conclusion四個段落總字數上限為350字，超過者無法成功投遞。(在論文內容左側有字數之提醒)

* 癌症登記

http://tcr.cph.ntu.edu.tw/main.php?Page=A5

99年以後之年報，請至國民健康署網站下載

http://www.hpa.gov.tw/BHPNet/Web/Stat/Statistics.aspx


** 年度報告

101年癌症登記年報.pdf

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201504290001


100年癌症登記年報.zip

http://www.hpa.gov.tw/BHPNet/Web/Stat/StatisticsShow.aspx?No=201404160001


** text extract

 53,553  26  61  55  85  178  219  304  714 1,257 2,324 3,741 5,321  6,458 6,816 5,320 6,309 5,800 5,047 3,518
 43,141  21  85  50  67  133  217  447  981 1,693 2,732 4,171 4,859  5,337 5,019 3,805 4,224 3,858 3,031 2,411
 96,694  47  146  105  152  311 436 751 1,695 2,950 5,056 7,912 10,180 11,795 11,835 9,125 10,533 9,658 8,078 5,929



** 解壓縮zip檔，產生亂碼

emerge app-arch/p7zip

emerge app-text/convmv


http://www.ubuntu-tw.net/modules/newbb/viewtopic.php?topic_id=91908&forum=7

[分享] 解壓縮zip檔，產生亂碼，如何解決的心得

下載範例檔案

LC_ALL=C 7z x Open_Data.zip 

convmv -f BIG5 -t UTF-8 -r Open_Data

convmv -f BIG5 -t UTF-8 -r Open_Data --notest

convmv -f BIG5 -t UTF-8 -r test

convmv -f BIG5 -t UTF-8 -r test --notest


LC_ALL=C 7z x 100年癌症登記年報.zip

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf

convmv -f BIG5 -t UTF-8 -r 100?~???g?n?O?~??.pdf --notest



* diigo

** outliner

| library | outliners |   |   |
|         |           |   |   |


What can you do with Outliner?
Organize what you have collected - links, notes, quotes, images, along with your own thoughts
Take meeting notes and arrange them efficiently
Organize quotes for your writing projects
