* The Ultimate Tar Command Tutorial with 10 Practical Examples

http://www.thegeekstuff.com/2010/04/unix-tar-command-examples/


** summary

| tar  cvf |       | .tar     |
| tar  tvf |       |          |
| tar  xvf |       |          |
|----------+-------+----------|
|          |       |          |
| tar zcvf | gzip  | .tar.gz  |
| tar ztvf |       | .tgz     |
| tar zxvf |       |          |
|----------+-------+----------|
|          |       |          |
| tar jcvf | bzip2 | .tar.bz2 |
| tar jtvf |       | .tbz     |
| tar jxvf |       | .tb2     |
|----------+-------+----------|
|          |       |          |
| tar Jcvf | xz    | .tar.xz  |
| tar Jtvf |       |          |
| tar Jxvf |       |          | 

** performance

tar zcvf nhird.tar.gz /mnt/sda5/nhird

tar jcvf nhird.tar.bz2 /mnt/sda5/nhird

tar Jcvf nhird.tar.xz /mnt/sda5/nhird

|     |   Gb |
|-----+------|
| gz  |  1.4 |
|     |      |
| bz2 | 0.95 |
|     |      |
| xz  |      |
|     |      |

** tar cvf


$ tar cvf archive_name.tar dirname/


In the above command:

c – create a new archive
v – verbosely list files which are processed.
f – following is the archive file name


** tar zcvf

$ tar cvzf archive_name.tar.gz dirname/

z – filter the archive through gzip

Note: .tgz is same as .tar.gz

| the same |
|----------|
| .tar.gz  |
| .tgz     |


** tar jcvf

$ tar cvfj archive_name.tar.bz2 dirname/

j – filter the archive through bzip2

gzip vs bzip2: bzip2 takes more time to compress and decompress than gzip. bzip2 archival size is less than gzip.

Note: .tbz and .tb2 is same as .tar.bz2

| the same |
|----------|
| .tar.bz2 |
| .tbz     |
| .tb2     |


** tar xvf

$ tar xvf archive_name.tar

x – extract files from archive


** tar zxvf

Use the option z for uncompressing a gzip tar archive.

$ tar xvfz archive_name.tar.gz


** tar jxvf

Use the option j for uncompressing a bzip2 tar archive.

$ tar xvfj archive_name.tar.bz2


** tar tvf

You can view the *.tar file content before extracting as shown below.

$ tar tvf archive_name.tar


** tar ztvf

You can view the *.tar.gz file content before extracting as shown below.

$ tar tvfz archive_name.tar.gz


** tar jtvf

You can view the *.tar.bz2 file content before extracting as shown below.

$ tar tvfj archive_name.tar.bz2



** tar xvf

The following command extracts only a specific file from a large tar file.

$ tar xvf archive_file.tar /path/to/file

$ tar xvfz archive_file.tar.gz /path/to/file

$ tar xvfj archive_file.tar.bz2 /path/to/file




** tar Jcvf

http://blog.gtwang.org/linux/linux-why-are-tar-archive-formats-switching-to-xz-compression-to-replace-bzip2-and-what-about-gzip/


tar.xz

壓縮 tar.xz：

tar Jcvf file_name.tar.xz dir_name

解壓縮 tar.xz：

tar Jxvf file_name.tar.xz


* tar lz4


app-arch/lz4



tar cvf - folderABC | lz4 > folderABC.tar.lz4

or

tar cvf - folderABC | lz4 - folderABC.tar.lz4

First one compresses silently, like gzip. Second one is a bit more lz4-specific, and will also display summarized compression stats.

http://stackoverflow.com/questions/24063846/how-to-use-tar-with-lz4


* performance


http://catchchallenger.first-world.info//wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO


Compression ratio

|   |  gzip | bzip2 |    xz | lz4   |
|---+-------+-------+-------+-------|
| 1 | 26.8% | 20.2% | 18.4% | 35.6% |
| 2 | 25.5% | 18.8% | 17.5% | 35.6% |
| 3 | 24.7% | 18.2% | 17.1% | 35.6% |


Compression time

|   | gzip | bzip2 | xz    | lz4  |
|---+------+-------+-------+------|
| 1 | 8.1s | 58.3s | 32.2s | 1.3s |
| 2 | 8.5s | 58.4s | 41.9s | 1.4s |
| 3 | 9.6s | 59.1s | 1m1s  | 1.3s |


Decompression time

|   | gzip | bzip2 | xz   | lz4  |
|---+------+-------+------+------|
| 1 | 3.5s | 3.4s  | 7.2s | 0.4s |
| 2 | 3s   | 15.7  | 6.8s | 0.3s |
| 3 | 3.2s | 15.9s | 6.7s | 0.4s |
